### ISSUE TITLE
the tcp connection will be closed?

### ISSUE THREAD

**Issue by flyq** [scs/substrate-api-client#102]
I ran the examples, and the api-client is so great! thanks!

I have a question:
the tcp connection will be closed? 
![image](https://user-images.githubusercontent.com/16486808/98352291-c8065080-2058-11eb-9b54-7e7f6e2be0fd.png)

the connect port is raised:
![image](https://user-images.githubusercontent.com/16486808/98352700-524eb480-2059-11eb-97b9-0bb95c398e06.png)

**Comment by clangenb** [comment]
hmm, are you sure these connections are from the api-client? Usually, substrate-nodes listen on port `9944` by default (which is also the default port for the api-client). Additionally, the connection should be closed automatically when the api-client stops running.

I am not familiar with `libp2p`, but could it be those ports?

**Comment by brenzi** [comment]
I think it could be the api-client because substrate probably reports source ports (which are arbitrary), not destination ports (which would be 9944). 
I have wondered about the number of connections also, but it seems polkadot-js api does the same.
@flyq which example did you run for the above screenshot?

**Comment by flyq** [comment]
I run the [test-node](https://github.com/scs/substrate-api-client-test-node) builded with 2020-10-06 nightly rust toolchain.

and run this substrate-api-client builded with nightly-2020-09-27-x86_64-unknown-linux-gnu toolchain.

actually, any "multi-connection" will cause this, such as example_benchmark_bulk_xt, example_get_blocks

**Comment by brenzi** [comment]
I take this as an observation, not an issue of substrate-api-client (because you could observe the same with polkadot-js api). Will close this. If you do have a problem with this behavior or think this is a bug, please reopen
