### ISSUE TITLE
can't get the block hash from get_storage_map

### ISSUE THREAD

**Issue by flyq** [scs/substrate-api-client#103]
### env
[test-node](https://github.com/scs/substrate-api-client-test-node),  built by rust nightly-2020-10-06-x86_64-unknown-linux-gnu. Add a map to make sure function of get_storage_map is ok.

[this client](https://github.com/scs/substrate-api-client), built by rust nightly-2020-09-27-x86_64-unknown-linux-gnu.

### log
run the example_get_storage:
```shell
cargo run --example example_get_storage
```
result:
```shell
Interacting with node on ws://127.0.0.1:9944

[+] block hash for blocknumber 2 is 0x0000000000000000000000000000000000000000000000000000000000000000
map: 5
```

### code
the example rust code:
```rust
// get StorageMap
    let result: Hash = api
        .get_storage_map("System", "BlockHash", 2u64, None)
        .or_else(|| Some(Hash::default()))
        .unwrap();
    println!("[+] block hash for blocknumber 2 is {:?}", result);
// get another StorageMap
    let result = api
        .get_storage_map("TemplateModule","SomeMap", 4_u32, None)
        .or(Some(0))
        .unwrap();
    println!("map: {:?}", result);
```
from above, the function get_storage_map is normal, buit can't get BlockHash

**Comment by brenzi** [comment]
why would you get the block hash like this? substrate deletes certain keys from the state after block production is complete (like block number and maybe also block hash?)
I'd suggest you use scs/substrate-api-client/blob/master/src/examples/example_get_blocks.rs

**Comment by flyq** [comment]
thanks, I want to test whether the get_storage_map is ok. Maybe I need learn more about Substrate.

**Comment by brenzi** [comment]
I realize now that the blockhash comes from our own example.

https://github.com/scs/substrate-api-client/blob/359e7769486479b77c8f9df198eeea36d5995825/src/examples/example_get_storage.rs#L40-44

 I guess that broke when we updated dependencies. Will reoprn this issue to get the example fixed.

**Comment by brenzi** [comment]
I can confirm that the example doesn't work for our substrate-2.0.0 release

The example says:
```
[+] block hash for blocknumber 42 is 0x0000000000000000000000000000000000000000000000000000000000000000
```
Which isn't correct. I guess this has to do with a change in state mapping. Will investigate

**Comment by brenzi** [comment]
the problem is probably caused by pruning:

https://github.com/paritytech/substrate/blob/a200cdb93c6af5763b9c7bf313fa708764ac88ca/frame/system/src/lib.rs#L1047-L1056

We may want to change our example to query a `map` which isn't pruned
