### ISSUE TITLE
Avoid always `Immortal`

### ISSUE THREAD

**Issue by AurevoirXavier** [scs/substrate-api-client#108]
https://github.com/scs/substrate-api-client/blob/master/src/extrinsic/mod.rs#L132

If an account gets killed (dust). And its nonce will reset to 0. The extrinsic can be repaid.

**Comment by brenzi** [comment]
also check discussion on subxt: https://github.com/paritytech/substrate-subxt/pull/204

**Comment by clangenb** [comment]
Mortality checkpoint can now be set: https://github.com/scs/substrate-api-client/blob/7b56455a23b2a98f7fb7113619000522fd86eae7/primitives/src/extrinsic_params.rs#L111
