### ISSUE TITLE
Pass adress and port independently to constructor.

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#109]
Change the `Api::new(url: String)` to `Api::new(address: &str, port: &str)`. Practice shows that this is more convenient as all our CLI`s fetch the url and the port independently, which leads to boilerplate code outside the Api.

Note: `&str` suffices, as we will assemble the `String` internally with `format!`

**Comment by haerdib** [comment]
@clangenb api-client now offers the function `new_with_port` for all rpc clients. Only took 3 years 🥳
