### ISSUE TITLE
add branch = "master" to substrate deps

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#114]
because of the following error, when compiling the encointer node:

```
warning: two git dependencies found for `https://github.com/paritytech/substrate.git` where one uses `branch = "master"` and the other doesn't; this will break in a future version of Cargo, so please ensure the dependency forms are
consistent
```

**Comment by clangenb** [comment]
Note: Removing the branch identifier everywhere is not an option. We must stick to the way substrate's handling it. as polkadot depends on substrate including branch identifier.

**Comment by brenzi** [comment]
as this is only a warning for now, I wouldn't take action right now.

**Comment by clangenb** [comment]
Unfortunately, it introduces duplicate deps when compiling the encointer-node.

**Comment by brenzi** [comment]
The problem is that currently, we toggle between 
```
branch = "master"
```
and 
```
branch="rococo-v1"
```
so there is trouble ahead, even if we re-introduce the former

**Comment by clangenb** [comment]
We might want to check this out. https://lib.rs/crates/diener

However, I believe we can mitigate the issue. The problem is that the encointer-primitives for the sybil-gate depend on polkadot.  If we feature-gate this module and its dependencies, we should be able to get rid of the polkadot dep.

Then at least we can reduce the occasions where this is an issue (i think it is only the encointer-parachain). And there it does not concern the api-client. Hence, I close this here.

**Comment by brenzi** [comment]
Diener doesn't help IMO because it is path based. But we would need to change that across repositories (without pushing anything)
