### ISSUE TITLE
create cargo workspace

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#121]
The number of crates has grown here. And `extrinsics` should be yet another crate #84. Hence, we should organize this repo as a cargo workspace

**Comment by trevor-crypto** [comment]
I would really like this to be modular so that I can use the api + extrinsics and implement my own jsonrpc client backend (non-websockets). Is that realistic?

I'm already hacking away on it, but I am afraid I do not know the library well enough to push this back upstream without guidance / assistance.

**Comment by clangenb** [comment]
Regarding the networking, I am not an expert, but I do think this is possible. The api-client could be generic over a trait `Client` that implements the basic methods to interface with a node, which is basically only:

https://github.com/scs/substrate-api-client/blob/3c8c04cd785b383dfbacb48a374503e644d13a08/src/lib.rs#L246

https://github.com/scs/substrate-api-client/blob/3c8c04cd785b383dfbacb48a374503e644d13a08/src/lib.rs#L531

These two methods are the foundation of every client request. So if you know how to implement these, you can do an alternate client implementation.

It would get a bit more involved, if you want to do async stuff, but I have something in mind also in this case. If I find time at some point, I would love to see the api-client async also.

Summarizing, to use another backend, you would not need to have more modularization, as the networking part is already quite self-contained.

I would offer guidance if you want to do that, as there is already #115 requested, which also would like to see another endpoint type.

**Comment by clangenb** [comment]
* Closed by #181
