### ISSUE TITLE
Wait raw event data lost

### ISSUE THREAD

**Issue by fewensa** [scs/substrate-api-client#122]
if i understand correctly, the subscribe_events usage here is like this 

```rust
let (sender, receiver) = mpsc::channel();
subscribe_events(sender).await?;
let raw_event = wait_for_raw_event("System", "ExtrinsicSuccess", Some(decoder), receiver).await?;
// the raw_event is result of subscribe_events
```

Have two questions.

***1. The subscribe_events/wait_for_raw_event is only can use once.***

https://github.com/scs/substrate-api-client/blob/3c8c04cd785b383dfbacb48a374503e644d13a08/src/rpc/client.rs#L87
when received data from websocket server, there closed connection. and the `wait-for_raw_event` received data will return
https://github.com/scs/substrate-api-client/blob/3c8c04cd785b383dfbacb48a374503e644d13a08/src/lib.rs#L575

of course, there can add loop to solve it.

```rust
loop {
  let (sender, receiver) = mpsc::channel();
  subscribe_events(sender).await?;
  let raw_event = wait_for_raw_event("System", "ExtrinsicSuccess", Some(decoder), receiver).await?;
  // the raw_event is result of subscribe_events
}
```

***2. event data lost***

https://github.com/scs/substrate-api-client/blob/3c8c04cd785b383dfbacb48a374503e644d13a08/src/lib.rs#L551-L584

There when received first data. will return. 

A simple data

```json
{"jsonrpc":"2.0","method":"state_storage","params":{"result":{"block":"0xd1f2447b2e84db3e2bcea28aee8ead0e75da3d89b4c8ebc2202f4fda4957fb97","changes":[["0x26aa394eea5630e07c48ae0c9558cef780d41e5e16056765bc8461851072c9d7","0x08000000000000005095a209000000000200000001000000000000e1f50500000000000000"]]},"subscription":"TYxO4H7BOvvkPzaS"}}
```
When received this data after decode will get two events.

```
RawEvent { module: "System", variant: "ExtrinsicSuccess", data: "5095a209000000000200" }
RawEvent { module: "System", variant: "ExtrinsicSuccess", data: "00e1f505000000000000" }
```

There will return first data. the second data lost

**Comment by brenzi** [comment]
it shouldn't be necessary to loop, because that can cause gaps when you miss data. @clangenb can you comment how to listen and keep the socket open?

**Comment by clangenb** [comment]
Oh sorry, I have seen this but completely forgot to come back to it. The `wait_for_event` method indeed only listens for the next matching event defined in the args and returns then. If you want to listen for events continuously, you can do the following:

```
println!("*** Subscribing to events");
let (sender, receiver) = channel();

let _eventsubscriber = thread::Builder::new()
    .name("eventsubscriber".to_owned())
    .spawn(move || {
        api.subscribe_events(sender).unwrap();
    })
    .unwrap();

println!("[+] Subscribed to events. waiting...");
let timeout = Duration::from_millis(10);
loop {
    if let Ok(msg) = receiver.recv_timeout(timeout) {
        if let Ok(events) = parse_events(msg.clone()) {
            /// do whatever you want with the events.
        }
    }
}

// where `Event`, `Hash` are types from your runtime.
type Events = Vec<frame_system::EventRecord<Event, Hash>>;

fn parse_events(event: String) -> Result<Events, String> {
    let _unhex = Vec::from_hex(event).map_err(|_| "Decoding Events Failed".to_string())?;
    let mut _er_enc = _unhex.as_slice();
    Events::decode(&mut _er_enc).map_err(|_| "Decoding Events Failed".to_string())
}

```

**Comment by fewensa** [comment]
Well, This is indeed a useful way, directly parse manually instead of  `wait_for_raw_event` method

**Comment by clangenb** [comment]
Happy to help, so can we close this issue?
