### ISSUE TITLE
Is support call crowdloan function?

### ISSUE THREAD

**Issue by ThreeAndTwo** [scs/substrate-api-client#124]
```
Crowdloan.contribute  
```

![image](https://user-images.githubusercontent.com/35927054/123239853-5c52f400-d512-11eb-84b1-2b0394ae2c94.png)

**Comment by clangenb** [comment]
It is not supported as a predefined extrinsic, but you can generically compose it yourself as we do it in this example:

https://github.com/scs/substrate-api-client/blob/master/src/examples/example_generic_extrinsic.rs

**Comment by ThreeAndTwo** [comment]
thanks a loy
