### ISSUE TITLE
error[E0609]: no field `modules` on type `RuntimeMetadataDeprecated`

### ISSUE THREAD

**Issue by ThreeAndTwo** [scs/substrate-api-client#126]
I wanna try run demo code for [this](https://github.com/scs/substrate-api-client/blob/master/src/examples/example_generic_extrinsic.rs)

info
![image](https://user-images.githubusercontent.com/35927054/123402184-0e092800-d5da-11eb-83ce-14777fab6d24.png)
![image](https://user-images.githubusercontent.com/35927054/123402249-1d887100-d5da-11eb-8f98-05463c0d7bd1.png)

thanks a lot

**Comment by clangenb** [comment]
Substrate deprecates immediately old runtime metadata. The current version is `V13`:

https://github.com/scs/substrate-api-client/blob/3c8c04cd785b383dfbacb48a374503e644d13a08/src/node_metadata.rs#L520-L523

You seem to use an older version here. You need to update your substrate deps.

**Comment by clangenb** [comment]
I have just checked, they didn't update the metadata. Update the api-client to version `0.6.0`. This should fix the error.

**Comment by ThreeAndTwo** [comment]
I checked the substrate-api-client version, it's the latest version is v0.5.0. am I incorrect?

**Comment by clangenb** [comment]
I don't know what you're looking at. Here in master it is v0.6.0.

https://github.com/scs/substrate-api-client/blob/master/Cargo.toml

**Comment by ThreeAndTwo** [comment]
I am looking at https://github.com/scs/substrate-api-client/tags.

**Comment by ThreeAndTwo** [comment]
I understood, thx

**Comment by clangenb** [comment]
Oh, we forgot to add the git tag last time. We'll make sure to add it, sorry for the inconvenience. @brenzi can you create the tag, I do not seem to have the rights to do that.

**Comment by clangenb** [comment]
Nvm, I could create the tag now. `v0.6.0` now exists!

**Comment by ThreeAndTwo** [comment]
thx.
