### ISSUE TITLE
Need help with reading a value from a StorageMap

### ISSUE THREAD

**Issue by vyorkin** [scs/substrate-api-client#128]
Lets say I have the following storage type:

```rust
#[pallet::storage]
#[pallet::getter(fn kitty_by_nonce)]
pub (super) type KittiesByNonce<T: Config> =
    StorageMap<_, Twox64Concat, u64, Kitty<T::Hash, T::Balance>, ValueQuery>;
```

Here is how I'm trying to read the `Kitty` with nonce `0`:

```rust
let kitty: Kitty = api
    .get_storage_map("Kitties", "KittiesByNonce", Some::<u64>(0), None)
    .unwrap()
    .unwrap();
```

Which results in error because the `get_storage_map` returns `None`.

**Comment by brenzi** [comment]
We just discovered a bug with twox64concat today. Will be fixed shortly by @haerdib

**Comment by vyorkin** [comment]
Just tried, the fix didn't help in my case. I can successfully read the `StorageValue`:
```rust
    let nonce: u64 = api
        .get_storage_value("Kitties", "Nonce", None)
        .unwrap()
        .or_else(|| Some(u64::default()))
        .unwrap();
```
But I can't get a value by key from a `StorageMap`:
```rust
    let kitty: Kitty = api
        .get_storage_map("Kitties", "KittiesByNonce", Some::<u64>(0), None)
        .unwrap()
        .unwrap();
```
The code above errors because the `get_storage_map` returns `None`

**Comment by haerdib** [comment]
Are you sure you need a ` Some()` in  the get_storage_map `Some::<u64>(0)`? 
As far as I can see you have defined `StorageMap<_, Twox64Concat, u64, Kitty<T::Hash, T::Balance>, ValueQuery>;` without an Option surrounding the u64 key.

**Comment by vyorkin** [comment]
:facepalm: Sorry, thank you :)
