### ISSUE TITLE
Peg substrate crates to revision

### ISSUE THREAD

**Issue by trevor-crypto** [scs/substrate-api-client#132]
Is it possible to peg all the `substrate` crates to a revision hash instead of using `master` in `Cargo.toml`? 

In my particular use case (and experience) it is difficult to use a substrate crate (ex. `sp-core`) in a library crate that will prepare some data for `substrate-api-client`, since there can be different versions of `sp-core` being used.

Another thing to consider is not committing `Cargo.lock` because `substrate-api-client` is a library, not an executable. This would also require using rev instead of branch for the substrate crates.

**Comment by brenzi** [comment]
pegging revisions causes a lot of things to break and duplicate deps. use cargo update -p sp-std  --precise <rev> instead.
the lockfile comes handy to see what revision of substrate has been tested

**Comment by clangenb** [comment]
@trevor-crypto FYI: https://github.com/scs/substrate-api-client/issues/114

Any rust crate that uses Polkadot is forced to use `branch= <branch-of-polkadot-branch>`.

**Comment by trevor-crypto** [comment]
@clangenb ok, thanks!

**Comment by trevor-crypto** [comment]
@brenzi @clangenb 
Sorry to comment on this again, but I'm running into the following issue while on a new branch which adds `pallet-staking` (I'm adding staking extrinsics and will push a PR eventually):

Adding the new crate is forcing a rev update it seems:
```
error: no matching package named `frame-executive` found
location searched: https://github.com/paritytech/substrate.git?branch=master
prerelease package needs to be specified explicitly
frame-executive = { version = "4.0.0-dev" }
required by package `node-template-runtime v3.0.0 (https://github.com/scs/substrate-api-client-test-node?branch=bump-to-polkadot-v0.9.2#7d14a36d)`
    ... which is depended on by `substrate-api-client v0.6.0 (/home/trevorarjeski/Workspace/substrate-api-client)`
```
Will this be an issue moving forward, if we need to specify the versions explicitly?

**Comment by clangenb** [comment]
The specific problem is that we specify version of the substrate crate:

https://github.com/scs/substrate-api-client-test-node/blob/7d14a36de9c47b80b46bc739b795c6b67c8cbd45/runtime/Cargo.toml#L19

And it is tagged to v3.0.0, while we don't reference any version in the api-client. I think we should remove the version over there also.

However, your problem should be resolved by running:

`cargo update -p sp-std --precise <previous commit form Cargo.lock>`, which downgrades the versions again.

**Comment by trevor-crypto** [comment]
Works! thanks for the help @clangenb :+1:
