### ISSUE TITLE
api-client never returns if node does not answer

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#134]
In case the node does not answer (or answers in an unexpted manner, due to whatever reason), the api-client will end up in a never ending loop here: https://github.com/scs/substrate-api-client/blob/master/src/lib.rs#L501 

A solution would be to exchange `.recv()` with `recv_timout()`. To provide maximum flexibility, either an extra function input parameter would be necessary (for example `Option<Duration>` [here](https://github.com/scs/substrate-api-client/blob/master/src/lib.rs#L491)) or an additional struct parameter could be introduced in the future [WsRpcClient](https://github.com/trevor-crypto/substrate-api-client/blob/rpcclient/src/std/rpc/ws_client/client.rs#L25)

**Comment by clangenb** [comment]
I think we could implicitly add a sensible default value for the timeout, but add a builder method to overwrite this, i.e.:

```
Api::new(client)
   .with_timeout(...);
```

**Comment by haerdib** [comment]
Blocked by #133 and #303
