### ISSUE TITLE
Could not decode `RuntimeMetadata::V12.0`

### ISSUE THREAD

**Issue by rise0chen** [scs/substrate-api-client#139]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StorageValueDecode(Error { cause: Some(Error { cause: Some(Error { cause: None, desc: "Decoding is not supported" }), desc: "Could not decode `RuntimeMetadata::V12.0`" }), desc: "Could not decode `RuntimeMetadataPrefixed.1`" })', src/examples/example_get_storage.rs:27:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

my node is https://github.com/substrate-developer-hub/substrate-node-template

**Comment by clangenb** [comment]
I am unsure what the reason is. Are you using master of the substrate-api-client?

Maybe the substrate-node-template is too new and is not yet supported by the substrate-api-client.

We assure that the example works for substrate revision: 1d7f6e12c651d776fc0dc1adefd007bb60f60b63

**Comment by rise0chen** [comment]
substrate 3.0 of crates.io use RuntimeMetadata::V12.0.
add, I have update substrate.
