### ISSUE TITLE
Decode extrinsics

### ISSUE THREAD

**Issue by Daelon02** [scs/substrate-api-client#151]
Hi, how we can decode extrinsic for get all values? Like 
```
{
  "sender": "some",
  "dest": "some",
  "amount": "some"
}
```

**Comment by clangenb** [comment]
The extrinsics formati is like that:

```
        UncheckedExtrinsicV4<Call:  Decode + Encode> {
            signature: Some((signed, signature, extra)),
            function: Call,
        }
```

In the context of balances transfer, call is a tuple like this:

```
type BalanceTransferFn = (CallIndex, Address, Compact<Balance>);
```

Currently, you'd need to implement it manually to retrieve sender, des, amount.

```
sender: xt.signature.unwrap().0,
dest: xt.call.1
amount: xt.call.2
```

Note: `signed` is a typo in the should and should be `signer`.

However, I suggest you simply listen for the `balances.transfer` event and extract the values from there? Or what is your use-case?

**Comment by Daelon02** [comment]
> The extrinsic format is like that:
> 
> ```
>         UncheckedExtrinsicV4<Call:  Decode + Encode> {
>             signature: Some((signed, signature, extra)),
>             function: Call,
>         }
> ```
> 
> In the context of balances transfer, the call is a tuple like this:
> 
> ```
> type BalanceTransferFn = (CallIndex, Address, Compact<Balance>);
> ```
> 
> Currently, you'd need to implement it manually to retrieve sender, des, amount.
> 
> ```
> sender: xt.signature.unwrap().0,
> dest: xt.call.1
> amount: xt.call.2
> ```
> 
> Note: `signed` is a typo in the code and should be `signer`.
> 
> However, I suggest you simply listen for the `balances.transfer` event and extract the values from there? Or what is your use-case?

We need save all extrinsics in our database, because if we use events, we cant get all transactions, because if our app shutdown, we cant parse latest blocks

**Comment by Daelon02** [comment]
We need get transactions from blocks, transactions or inBlock, or finallized

**Comment by Daelon02** [comment]
We need get what this extrinsic return

**Comment by clangenb** [comment]
This is actually not that straightforward. Do decode that successfully, you would first need to peek into the values of the `CallIndex = [u8;2]`. If you have access to the aggregated call enum from the runtime, this is much easier. Then you should be able to do decode the entire vector of extrinsics in the block like:

```let xt: Vec<UncheckedExtrinsicV4<RuntimeCallEnum>> = Decode::decode(&mut extrinsics_vec_encoded.as_slice())```
