### ISSUE TITLE
Upon "Future" status, api-client returns `Err(InvalidHexString)`

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#157]
If an extrinsic is placed in the future pool, the api-client will issue a [warning](https://github.com/scs/substrate-api-client/blob/2edd060c0a515718d62f3a78008b4123a5acefeb/src/std/rpc/ws_client/mod.rs#L206) and then end the process with a [None value](https://github.com/scs/substrate-api-client/blob/2edd060c0a515718d62f3a78008b4123a5acefeb/src/std/rpc/ws_client/mod.rs#L207).

The None is turned into an [empty String](https://github.com/scs/substrate-api-client/blob/2edd060c0a515718d62f3a78008b4123a5acefeb/src/std/rpc/ws_client/mod.rs#L293) and sent back [via channel](https://github.com/scs/substrate-api-client/blob/2edd060c0a515718d62f3a78008b4123a5acefeb/src/std/rpc/ws_client/mod.rs#L299)

If one is waiting until "Finalized", the api client [expects an hex string](https://github.com/scs/substrate-api-client/blob/2edd060c0a515718d62f3a78008b4123a5acefeb/src/std/rpc/ws_client/client.rs#L64). However, because the return value is empty it will finally return an hex error `Err(InvalidHexString(InvalidStringLength))`.

```bash
[2021-09-01T14:29:02Z DEBUG substrate_api_client::rpc::client] got msg {"jsonrpc":"2.0","method":"author_extrinsicUpdate","params":{"result":"future","subscription":"18PvlhIHlZgUWISr"}}
[2021-09-01T14:29:02Z WARN  substrate_api_client::rpc::client] extrinsic has 'future' status. aborting
[2021-09-01T14:29:02Z DEBUG substrate_api_client::rpc::client] Thread end result :Sender { .. } value:None
[2021-09-01T14:29:02Z INFO  substrate_api_client] finalized:
[2021-09-01T14:29:02Z ERROR substratee_worker::polkadex_db] [<] Extrinsic got finalized. Hash: Err(InvalidHexString(InvalidStringLength))
```

Should the client wait until future has been finalized? Or should we change the return value handling?

**Comment by brenzi** [comment]
well, future is a tricky one. can be caused by a nonce errror (nonce too high) and then you just wait forever. I'd suggest to tread future like an error when waiting for InBlock or Finalized

**Comment by Gauthamastro** [comment]
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/17110878/133919695-11435184-4993-4a18-a4ed-8af294926fab.png">

I am having a similar error but I believe it's coming because of an extrinsic verification error in the node.

 this is the extrinsic, I am trying to call

```
let operational_call: UncheckedExtrinsicV4<_> = compose_extrinsic!(
        api.clone(),
        "PDEXMigration",
        "set_migration_operational_status",
        true
    );

    let sudo_operational_call: UncheckedExtrinsicV4<_> = compose_extrinsic!(
        api.clone(),
        "Sudo",
        "sudo",
        operational_call
    );

api.send_extrinsic(sudo_operational_call.hex_encode(), XtStatus::InBlock).unwrap();
```

**Comment by brenzi** [comment]
@Gauthamastro you are wrapping an entire extrinsic in your sudo extrinsic. this can't work. use compose_call instead. See https://github.com/scs/substrate-api-client/blob/master/src/examples/example_sudo.rs

your issue is unrelated

**Comment by Gauthamastro** [comment]
Ahh yes!! I missed that. Thanks @brenzi

**Comment by haerdib** [comment]
I'm proposing the following solution:
1. return an error for now, but one that indicates that a Future has been returned, not an `InvalidHexString`
2. After introducing a timeout (https://github.com/scs/substrate-api-client/issues/134) the api client could be expanded to allow two modi:
    - allow future: wait until finalized or timeout
    - don't allow future: return an Error upon future
but this should be done in a separate task.
