### ISSUE TITLE
Can I send an extrinsic that I don't known sign key of it?

### ISSUE THREAD

**Issue by raindust** [scs/substrate-api-client#161]
I'm trying to separate the process of construct an extrinsic and sent to chain according to https://github.com/scs/substrate-api-client/blob/master/src/examples/example_compose_extrinsic_offline.rs

What I want is to construct the extrinsic with account A, and send it by account B. I noticed that the nonce value [here](https://github.com/scs/substrate-api-client/blob/master/src/examples/example_compose_extrinsic_offline.rs#L56) should be set by myself, and what else should I have to modify? I noticed the `send_extrinsic` method in API is using "author_submitAndWatchExtrinsic" substrate RPC interface, is it ok to send an extrinsic that is not signed by myself, or should I have to use another substrate RPC interface (such as "author_submitExtrinsic", I can't get the differences between these two RPC interfaces)?

**Comment by clangenb** [comment]
There is no problem, we also do the same, i.e., construct the extrinsic with `compose_extrinsic_offline` and then send it afterwards. The `send_extrinsic` method does need the `signer` to be set. So you don't send it with another account, you just send it.

**Comment by raindust** [comment]
Thanks for the reply @clangenb , I have tested successfully. It seems like if I maintain the nonce myself, the nonce value must be started at `0`, I started at `1` and it failed.
