### ISSUE TITLE
no branch or tag referencing stable version of substrate

### ISSUE THREAD

**Issue by aregng** [scs/substrate-api-client#162]
Almost all branches and tags of this repo refer to the master branch of substrate repo.
Recently substrate master branch is updated in a way that  it is not compile-compatible with the current master and other branches of this repo.

Could you please provide branches/tags which refer to stable substrate code-base and not master branch which is prone to frequent changes.

**Comment by trevor-crypto** [comment]
See here for more info: https://github.com/scs/substrate-api-client/issues/132

You can look in the `substrate-api-client` [lock file](https://github.com/scs/substrate-api-client/blob/28c4977bcc65117a47993564996cb99da552bced/Cargo.lock#L2962) for the revision you need to use in your own lock file.

`cargo update -p sp-std --precise f651d45ce57`

**Comment by brenzi** [comment]
We decided not to make releases. Just use the way @trevor-crypto described to pick your upstream commit.
Should parity/substrate decide to follow semver, and should cargo [improve their handling of git dependencies](https://github.com/rust-lang/cargo/issues/7497), we may change our mind.

**Comment by haerdib** [comment]
With #168 the curent error cargo update error should be fixed :-)

**Comment by haerdib** [comment]
We now have polkadot branches (latest: https://github.com/scs/substrate-api-client/tree/polkadot-v0.9.27) , so this should not be an issue any more.
