### ISSUE TITLE
Can I get block related info when listening event?

### ISSUE THREAD

**Issue by raindust** [scs/substrate-api-client#163]
I can listen to substrate events by following [example_event_callback](https://github.com/scs/substrate-api-client/blob/master/src/examples/example_event_callback.rs), but I can't find how to get block info (such as block height or block hash) about the event. 
Is there a way to get such info?

**Comment by clangenb** [comment]
Hmm, as far as I know, you can't unless there is a specific event from the some (e.g. system) pallet, which does exactly that.

**Comment by raindust** [comment]
I see, thanks
