### ISSUE TITLE
Can't connect:Metadata Conversion Issue

### ISSUE THREAD

**Issue by kroos47** [scs/substrate-api-client#171]
Yeh I was testing out the substrate api and I was getting this error 
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Metadata(Conversion(InvalidVersion))', src/main.rs:13:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

from the code I ran: 
```
`use substrate_api_client::{Api};
use clap::{load_yaml, App};
use substrate_api_client::rpc::WsRpcClient;
use substrate_api_client::sp_runtime::app_crypto::sp_core::sr25519;
fn main() {
    // instantiate an Api that connects to the given address
    let url = "ws://127.0.0.1:9944";
    env_logger::init();
    let client = WsRpcClient::new(&url);
    let api = Api::<sr25519::Pair, _>::new(client).unwrap();
`

```
Any fix for this?

**Comment by clangenb** [comment]
I reckon that you run the example against a node that is either very new or too outdated. Try setting the node's version to the commit referenced in our `Cargo.lock`.

**Comment by kroos47** [comment]
Oh yes!! Thanks
