### ISSUE TITLE
Metadata v14 support

### ISSUE THREAD

**Issue by convexman** [scs/substrate-api-client#173]
I'm trying to use this library against westend node (for example public websocket wss://westend.api.onfinality.io/public-ws)

It's returning metadata in v14 format which gives conversion error (https://github.com/scs/substrate-api-client/blob/master/src/std/node_metadata.rs#L697)

I wonder if support for v14 is planned? I guess soon Kusama and Polkadot will adopt v14 format too

**Comment by brenzi** [comment]
We do plan to support it but no promises on timing. PR welcome ;-)

**Comment by clangenb** [comment]
I will start working on this. If anybody has a WIP, I will be happy to have a look at it.

**Comment by trevor-crypto** [comment]
@clangenb I only have the linked "hack" above which tries to follow the logic that is already there (minus the Events stuff)

**Comment by kostekIV** [comment]
Hi, @clangenb I started looking at this and I would be happy to help. Just let me know if you are fine with it :)

**Comment by clangenb** [comment]
Thanks, but I am almost finished. :) I might file a pr today.

This is the wip branch: https://github.com/scs/substrate-api-client/tree/metadata-v14

The diff to master is terrible though, as it is built upon the other branches.
