### ISSUE TITLE
compose_extrinsic_offline! (without networking requirement)

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#18]
SubstraTEE-worker needs to compose extrinsics within an enclave without holding an api object / without the possibility to query nonce and genesis hash or metadata

solution needed for:
  * https://github.com/scs/substraTEE-worker/blob/56d29e014ffe58039ec66d8d890280b3728f9974/enclave/src/attestation.rs#L569
  * https://github.com/scs/substraTEE-worker/blob/56d29e014ffe58039ec66d8d890280b3728f9974/enclave/src/lib.rs#L352

currently, nonce and genesis hash do not need to be supplied to `compose_extrinsic`. Instead, the macro queries these directly from the node.

We need another `compose_extrinsic_offline` function that takes nonce and genesis hash as arguments. 

This might get more complicated as metadata is also unknown to the substraTEE-enclave today.
We might want to hard-code the call as well, so we don't need `compose_call!`.

This way we could use our new function similar to this:
```
    let xt = compose_extrinsic_offline!(
        AccountKey::new("//Alice", Some(""), CryptoKind::Ed25519),
        Call::SubstraTEERegistry(SubstraTEERegistryCall::register_enclave(...)),
        nonce,
        genesis_hash
    );
```

**Comment by brenzi** [comment]
@clangenb may I ask you to comment on the suggested function? Do you see a better way?

**Comment by clangenb** [comment]
I think this is a very viable solution and should not take to long to implement.

I don't know why you think that it gets more complicated without knowing the metadata. If the `Calls` are imported, the metadata is not needed, or do I miss something?

I am unsure though, if we run into `[no_std]` issues if we use the macro in the enclave. Regardless, a `compose_extrinsic_offline` should be implemented.

**Comment by brenzi** [comment]
> I don't know why you think that it gets more complicated without knowing the metadata. If the `Calls` are imported, the metadata is not needed, or do I miss something?

true. Was meant to be *problem statement* followed by *solution*
