### ISSUE TITLE
Can't bump substrate due to std-leackage from ss58Registry in sp-core

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#188]
* https://github.com/paritytech/substrate/issues/10362

**Comment by haerdib** [comment]
Seems to have been fixed already: https://github.com/paritytech/substrate/blob/master/primitives/core/Cargo.toml#L71

**Comment by clangenb** [comment]
Ah, yes I can confirm the api-client did compile with the newest substrate
