### ISSUE TITLE
make `node-api` `no_std` compatible

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#190]
I have peeked (1.5h) into making the `node-api` stuff no_std compatible. It should be possible, but implies some rewriting of the code:

* The core change would be handling `PortableForm` differently. This is kind of hard now, as it behaves differently in `std` and `no_std`, hence the surrounding code, needs to be able to handle that.

However, strictly `no_std` is not possible either, as `sp-io`, which lies at the very bottom of the `substrate` deps, assumes wasm in `no_std`, which means it will not compile to `std`, without its `std` feature.

The nice thing is, if the `node-api` is `no_std` compatible, we can make many features no-std compatible of the api-client.

I reckon the overall effort to be a day for that (me doing it). It might be worth to try.

**Comment by lucgerrits** [comment]
Hi, I've tried to build a basic program to send a transaction using `no_std`. Hopefully to later embed it on a small IoT kind of device.
https://gist.github.com/lucgerrits/cccd91ae629441de141b8bc49fc61e3f

Indeed it doesn't like `no_std` much, getting the following error:
```
error[E0599]: no method named `to_owned` found for reference `&ac_node_api::metadata::PalletMetadata` in the current scope
  --> src/set_storage_no_std.rs:48:39
   |
48 |       let xt: UncheckedExtrinsicV4<_> = compose_extrinsic!(
   |  _______________________________________^
49 | |         api.clone(),
50 | |         "KeyvalueModule",
51 | |         "store",
52 | |         key.as_bytes().to_vec(),
53 | |         val.as_bytes().to_vec()
54 | |     );
   | |_____^ method not found in `&ac_node_api::metadata::PalletMetadata`
   |
   = help: items from traits can only be used if the trait is in scope
   = note: this error originates in the macro `$crate::compose_call` (in Nightly builds, run with -Z macro-backtrace for more info)
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
4  | use sp_core::sp_std::borrow::ToOwned;
   |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `substrate-client` due to previous error
```

I'm willing to give a try to edit `node-api` but I'm new to Rust so gonna take days lol. If news I'll post it here...

**Comment by clangenb** [comment]
It is not my intention to discourage, but if you are not experienced with rust, substrate and no_std, this will be a very tough one. :)

**Comment by lucgerrits** [comment]
I'm okish in Rust and Substrate, but not with `no_std` at all...
