### ISSUE TITLE
create a library 

### ISSUE THREAD

**Issue by electronix** [scs/substrate-api-client#2]
the code must be compiled into a library (crate) that can be used by substraTEE-client and substraTEE-worker

**Comment by brenzi** [comment]
done. 

https://github.com/scs/substrate-api-client/blob/master/README.md

What works:
  * reading storage
  * sending pre-generated extrinsics
  * sending a balances::transfer() call extrinsic
  * listening to events and executing code upon new events

yet TODO:
  * sending a substraTEE-proxy call with payload
  * *compose-extrinsic* as its own `no_std` library
