### ISSUE TITLE
how to estimate  transaction gas fee ?

### ISSUE THREAD

**Issue by raojianli** [scs/substrate-api-client#200]

**Comment by clangenb** [comment]
We have two methods that return the fee of a tx:

* https://github.com/scs/substrate-api-client/blob/a9bc023806b175fe0bc996326b5f4635c427cbcd/src/std/mod.rs#L454
* https://github.com/scs/substrate-api-client/blob/a9bc023806b175fe0bc996326b5f4635c427cbcd/src/std/mod.rs#L471

**Comment by clangenb** [comment]
Is this what you were looking for?
