### ISSUE TITLE
Deserializing(Error(\"missing field `stateVersion`\", line: 1, column: 490))

### ISSUE THREAD

**Issue by raojianli** [scs/substrate-api-client#201]

**Comment by clangenb** [comment]
I believe your node is incompatible with the api-client's substrate version. You can check the substrate version that is guaranteed to work in the Cargo.lock

**Comment by raojianli** [comment]
substrate-api-client version must be the same as the substrate version?

**Comment by brenzi** [comment]
yes, the substrate commits should match to be sure. If you need a specific commit, you can fork api-client and adjust the commit in Cargo.lock
