### ISSUE TITLE
Use `parity/substrate:latest` docker image in CI.

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#204]
This will reduce the amount the CI runs by 25 minutes. It also seems to track the latest substrate master branch.

Instead of building the substrate node ourselves, we should just run the examples against the docker image.

This whole build-step can be removed: https://github.com/scs/substrate-api-client/blob/03251c4332c5b7fa4d952f772ba4469db1b824b7/.github/workflows/ci.yml#L55

And here we can use the docker image: https://github.com/scs/substrate-api-client/blob/03251c4332c5b7fa4d952f772ba4469db1b824b7/.github/workflows/ci.yml#L127

**Comment by echevrier** [comment]
Check also if https://github.com/scs/substrate-api-client/issues/239 can be done

**Comment by clangenb** [comment]
Yes, this would also fix #239

**Comment by clangenb** [comment]
This task has partly been solved in #249.

We fail a sending extrinsics and decoding blocks because of the extrinsics.

I think this is because the `SignedExtra` in the node-template does not contain the `CheckNonZero` sender yet. Hence, I think this should be solved if we update the `SubstrateDefaultSignedExtra` to include that.
