### ISSUE TITLE
Tutorial doesnt work

### ISSUE THREAD

**Issue by trusch** [scs/substrate-api-client#205]
I just tried the tutorial, but I cant get a simple example to compile because of dependency issues.

The tutorial states that I only need one dependency but even in the Cargo.toml there are more and even this doesnt compile.

The final error I saw was this:
```
error: no matching package found
searched package name: `sp-runtime`
prerelease package needs to be specified explicitly
sp-runtime = { version = "4.1.0-dev" }
location searched: https://github.com/paritytech/substrate.git?branch=master
required by package `substrate-api-client v0.6.0 (https://github.com/scs/substrate-api-client.git#fbd21c77)`
    ... which satisfies git dependency `substrate-api-client` of package `scs-test v0.1.0 (/home/trusch/projects/scs-test)`
```

Any input on how to make use of this otherwise super looking lib would be really appreciated!

**Comment by brenzi** [comment]
which tutorial did you attempt?

may I ask you to try using the Cargo.lock file from our repo?
Your error indicates that you are not using the precise substrate commit we use. Unfortunately that's not generally possible.

**Comment by clangenb** [comment]
This is because substrate literaly just now (https://github.com/paritytech/substrate/commit/823c2533612e9bab7ac5e4f57a7c5daa762c00a5) bump versions of sp-runtime. 

If the version in our Cargo.toml can't be found on latest master it will unfortunately not found the dependency.

I have made the update in this branch: https://github.com/scs/substrate-api-client/tree/cl/bump-deps

**Comment by clangenb** [comment]
Edit: the keystore does not yet compile with due to breaking changes, but the main binary does. Will fix it soon.

**Comment by trusch** [comment]
@brenzi I tried the tutorial thats linked from the main README.md

@clangenb Thanks a lot, I'll give it a try!

**Comment by anthonybuckle** [comment]
@clangenb Hi, I attempted to use your bump-deps branch. When I tried the example: example_print_metadata.rs. It gives the following error. I tried it against a local dev build of substrate-node-template and karura node: wss://karura.api.onfinality.io/public-ws. The error happens on line 35 or during creating the api. Any thoughts?

`Interacting with node on wss://karura.api.onfinality.io/public-ws

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Deserializing(Error("missing field `stateVersion`", line: 1, column: 429))', src/examples/example_print_metadata.rs:35:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by anthonybuckle** [comment]
Regarding the above error about "missing field stateVersion". When the RuntimeVersion is being generated, some nodes will not return a stateVersion. This causes creating a new api to fail. Not sure what the correct fix is, but one workaround is to set sp-version to the following in Cargo.toml.

`sp-version = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate.git", package = "sp-version", optional = true, rev = "d36550a8da62fc968fac415c3379ad95d85105d1" }
`

**Comment by ryanjackgit** [comment]
I used this this branch:[https://github.com/scs/substrate-api-client/tree/cl/bump-deps](url),created a new test project,It's Cargo.toml is :

[package]
name = "xxxxxxxxx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hex = "0.4"
web3 = "0.16.0"
tokio = { version= "1", features = ["full"] }
dotenv = "0.15.0"

tracing-subscriber = { version="0.3.3" , features = ["env-filter"] }

tracing = "0.1.29"


anyhow = "1.0.51"

hex-literal = "0.3.4"
bytes = "1.1.0"

substrate-api-client = { path="../substrate-api-client-deps-version/substrate-api-client" }



when I compile test example :  example_print_metadata.rs,   error is : 

   Updating git repository `https://github.com/paritytech/substrate.git`
    Updating git repository `https://github.com/paritytech/frame-metadata.git`
    Updating crates.io index
error: failed to select a version for the requirement `frame-metadata = "^14.0.0"`
candidate versions found which didn't match: 15.0.0
location searched: Git repository https://github.com/paritytech/frame-metadata.git?branch=main
required by package `substrate-api-client v0.6.0 (/home/ryan/mydata/srcrust/substrate-api-client-deps-version/substrate-api-client)`

How to resolve it?  Thanks

**Comment by TJ-alchemist** [comment]
Faced the same issue with missing field `stateVersion`. Refer [**link**](https://github.com/scs/substrate-api-client/issues/229) for solution.

**Comment by clangenb** [comment]
I believe this was a problem with some specific combination of substrate versions. As we have upgraded the api-client several times since then, I think this is no longer relevant.
