### ISSUE TITLE
Which is the proper query to call query_storage_map and get an iterable?

### ISSUE THREAD

**Issue by johnuopini** [scs/substrate-api-client#227]
If i have a storage_map_query and i want to omit the option i usually get a vac of tuples through JS, i tried passing Vec<(K,V)> to the query storage map method but i always get a storage decode error, which is the proper way of getting a paginated result?

**Comment by clangenb** [comment]
This is not yet implemented on our side. It would require something like:

https://github.com/paritytech/subxt/blob/698f0242f3620a2b160d232667474c5e4acc89ee/subxt/src/rpc.rs#L278-L288

Together with the code following this line: https://github.com/paritytech/subxt/blob/698f0242f3620a2b160d232667474c5e4acc89ee/subxt/src/storage.rs#L223
