### ISSUE TITLE
Keep track of matching version to substrate framework

### ISSUE THREAD

**Issue by ivanceras** [scs/substrate-api-client#235]
I'm back to using this client again, but I couldn't make it work against the latest substrate framework. If anyone had a working version which uses a tagged version of the substrate framework rather than master it would be really helpful.

We can list down a compatible version of this client to their corresponding substrate version counterpart.

**Comment by haerdib** [comment]
Are you perhaps looking for a polkadot release branch? https://github.com/scs/substrate-api-client/tree/polkadot-v0.9.19

We will keep following the release branches. v0.9.20 will soon be coming.
