### ISSUE TITLE
Support single threaded strategy for sending extrinsics

### ISSUE THREAD

**Issue by fixxxedpoint** [scs/substrate-api-client#240]
Current implementation uses `thread/connection per extrinsic` strategy, i.e. [src/std/rpc/ws_client/client.rs](https://github.com/scs/substrate-api-client/blob/ab586d8be719243aa29503ec8c7b1457b2cd0830/src/std/rpc/ws_client/client.rs#L160). Please, support a single threaded strategy as well (or provide some easy method allowing to customize this behavior). We were trying to use this library for some flooding and benchmarking scenarios, but our nodes were overwhelmed by the number of connections spawned by it.

**Comment by clangenb** [comment]
This has been solved in #262 as good as we can with the current libraries.
