### ISSUE TITLE
More robust error handling

### ISSUE THREAD

**Issue by fixxxedpoint** [scs/substrate-api-client#241]
Receiving some unexpected error/msg (e.g. a json message without the `error` field) makes the calling thread panic, [src/std/rpc/ws_client/mod.rs](https://github.com/scs/substrate-api-client/blob/ab586d8be719243aa29503ec8c7b1457b2cd0830/src/std/rpc/ws_client/mod.rs#L342). Instead of panicing, please consider handle it some other way, e.g. return some `unknown error`.

**Comment by clangenb** [comment]
Yes, this is legacy from our very early rust days. I agree that this should be improved.
