### ISSUE TITLE
Signing a transaction using a custom account instead of Alice or Bob.

### ISSUE THREAD

**Issue by TJ-alchemist** [scs/substrate-api-client#245]
I have been using using Alice as the signer for signing / making all the transactions.
Is there a way where i can use my own real / dummy account to sign transactions?

**Comment by tolltronix** [comment]
I assume you can just create your own polkadot wallet.

**Comment by TJ-alchemist** [comment]
True. I have created a wallet.
But how do i access my account from within the client.
Does my account get added to the AccountKeyring?

**Comment by tolltronix** [comment]
Do you use the polkadot.js web client to view the Alice and Bob accounts?

**Comment by TJ-alchemist** [comment]
> Do you use the polkadot.js web client to view the Alice and Bob accounts?

Yes, I use the polkadot.js web explorer.

**Comment by TJ-alchemist** [comment]
> When you create your new account just select the "Use on any network" and you should just be able to use it is you do your Alice and Bob account. If I am missing your point I apologise.

Yes, my setting for the wallet is set to **"Use on any network"** and using it as Alice or Bob is what I'm hoping to achieve. But the thing is that in order to achieve the needful i first need to get the account information of my wallet, so I want to know if there is a way to do that in the API client?

**Comment by brenzi** [comment]
This crate doesn't manage accounts. But please have a look at how we use it for encointer cli:
https://github.com/encointer/encointer-node/blob/87adbc9cd438fc36ddff5b56221e83e4dcf189fa/client/src/main.rs#L122

**Comment by brenzi** [comment]
Or check out how we use private keys directly: 
https://github.com/scs/substrate-api-client/pull/216/files#

**Comment by TJ-alchemist** [comment]
> Or check out how we use private keys directly: https://github.com/scs/substrate-api-client/pull/216/files#

This will be really useful. Thank you @brenzi

**Comment by TJ-alchemist** [comment]
Thank you @tolltronix for your responses. It gave much needed clarity.
