### ISSUE TITLE
How to re-establish the connection after listen event connection is lost?

### ISSUE THREAD

**Issue by ryanjackgit** [scs/substrate-api-client#246]
how to know the  listen event connection is lost.

**Comment by clangenb** [comment]
This is unfortunately not handled yet. You simply get an error if you want to talk to the chain and the connection has been lost... Happy to receive a PR fixing this!

**Comment by haerdib** [comment]
This can be handled with the newly introduced tungestenite client (#355), or, as of #354, when a `None` is returned upon a `subscription.next()` call.
E.g. like in this function :
https://github.com/scs/substrate-api-client/blob/ad11c012cc1a0bfd8d8f0619d1354800d99c6727/src/api/subscription.rs#L122-L126
an Error is returned if the connection is lost. 

So in these cases (None or Err return value) one could implement an exception handler that reconnects automatically.

I hope this fulfills the requirements of this issue. If not, please reopen.
