### ISSUE TITLE
Getting InvalidHexString(InvalidStringLength) while calling Extrinsic

### ISSUE THREAD

**Issue by zktony** [scs/substrate-api-client#254]
While running follwing code:-
```
let xt: UncheckedExtrinsicV4<_, _> = compose_extrinsic!(
                        self.api.clone(),
                        "DEMO",
                        "submit_sp",
                        signature
                    );
                    // send and watch extrinsic until InBlock
let tx_hash = self
                  .api
                  .send_extrinsic(xt.hex_encode(), XtStatus::InBlock);
```
This is what I am getting in error :-
`InvalidHexString(InvalidStringLength)`
Not sure why it is failing. Can I somehow get the reason for failure?

**Comment by haerdib** [comment]
Did you try to set the log output to debug / trace in the api client? E.g. export RUST_LOG=error,substrate_api_client::rpc::client=debug

Might be related to https://github.com/scs/substrate-api-client/issues/157

**Comment by zktony** [comment]
Thanks, @haerdib. Found the issue.
