### ISSUE TITLE
drop dependency of examples on test node_runtime crate

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#26]
It is cumbersome to fix dependency issues because we import substrate-test-runtime

1. the build script enforces wasm build which is not necessary here
1. too many dependencies are added for only a fow type definitions

**Comment by brenzi** [comment]
done, except `example_contracts.rs` which depends on runtime's `Event` type. Can we define that ourselves? If I use `node_runtime::Event` it won't recognize a contract Event - obviously.

https://github.com/scs/substrate-api-client/tree/no_std_rstd

**Comment by clangenb** [comment]
We can do that. The event enum is constructed in the same manner as the call enums, which can therefore be constructed from the metadata. I reckon approximately 2-3 ours to have that work. 

Would do that with a macro in order handle the dynamic argument types.

**Comment by brenzi** [comment]
Unfortunately, the root cause why we have to disable the contract example right now is still an open issue: 
https://github.com/rust-lang/cargo/issues/6571

So, if we can work around the Event enum dependency easily, that'd be great
