### ISSUE TITLE
get_grandpa_justification is returning None

### ISSUE THREAD

**Issue by zktony** [scs/substrate-api-client#268]
Hey, 
get_grandpa_justification method provided by the client is returning `None` `api.get_grandpa_justification(signed_block.block.header.number)`. Though I can access it using polkadot.js

**Comment by haerdib** [comment]
Just to make sure: The block you're accessing via `api.get_grandpa_justification(signed_block.block.header.number)` does contain a grandpa justification? Depending on your substrate node settings, only every xth block contains a justification. 

Example of a block with a justification:
![grafik](https://user-images.githubusercontent.com/73821294/182405269-5fd22596-4506-4ed0-b2ad-08836b5eb5f3.png)

(Rococo Block Nr 1,313,373: 
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/explorer/query/0x0e37ea669c7f20b7d989532220da5ce2fc762c9a888f6104bee9972420deb54d)

**Comment by haerdib** [comment]
@zktony is this still a problem?

**Comment by haerdib** [comment]
Closing this as answered for now. Please reopen if it's still a problem.
