### ISSUE TITLE
Support wasm

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#272]
Previous work done: https://github.com/scs/substrate-api-client/pull/48

**Comment by Niederb** [comment]
One issue is that `substrate` has a dependency on `wasmtime`. This leads to a compilation error, but it probably does not make sense to compile a webassembly runtime with webassembly to begin with. So we would have to configure our code such that the dependency is not needed.

Compilation error:
```
...
cargo:warning=src/helpers.c:1:10: fatal error: 'setjmp.h' file not found
...
```

**Comment by haerdib** [comment]
Okay. To summarize:
- the api-client is wasm compatible in no-std mode ✔️ 
- To make std mode wasm compatible we would have to either
    1. get rid of sp-core / sp-io dependencies
    2. only depend on no-std part of spi-io, sp-core (not guaranteed though that it stops here, because the runtime is compiled to wasm in no-std mode)

Correct?

**Comment by Niederb** [comment]
Close this for now. See #513 for a follow up issue
