### ISSUE TITLE
substrate-test-nodes project used by tutorial is deprecated

### ISSUE THREAD

**Issue by rlaferla** [scs/substrate-api-client#275]
substrate-test-nodes project used by tutorial is deprecated.  it also fails to build on macOS w/M2 cpu because of the ring v0.14.6 dependency.   the tutorial needs to be updated to show how to use the api-client perhaps with the standard substrate node template.

**Comment by rlaferla** [comment]
Also, the readme mentions:

_You can download our node artifact from our GitHub Actions CI, which can be found in the 'Actions' tab._

So where is this in the Actions tab exactly?

**Comment by clangenb** [comment]
Thanks for reminding us!

This is the actions tab. Then you choose the newest master run, scroll down, and you fill find the artefact:
![image](https://user-images.githubusercontent.com/37865735/189275488-895c1bc7-90fd-41b3-952b-dd1012090db5.png)

However, if the node from the tutorial does no longer compile, we will deprecate the tutorial altogether I guess.

Instead, I suggest having a look at the [examples](https://github.com/scs/substrate-api-client/tree/master/examples). They will work with the most with the standard substrate-node template.

**Comment by clangenb** [comment]
I have removed the tutorial in #276, and tried to make it clearer where you can find the actions tab. :)
