### ISSUE TITLE
Be fully `no_std` compatible (except for ws rpc)

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#279]
Would include hosting a ws client in no-std. To my knowledge, this is not yet available as a library.

**Comment by clangenb** [comment]
We do not necessarily need a ws-client, just any networking interface that implements the [RpcClient](https://github.com/scs/substrate-api-client/blob/b91d78b53fdc3a05b3c1d1e7fe0fd6b8cfc0dd17/src/std/rpc/ws_client/client.rs#L37) or the [subscriber](https://github.com/scs/substrate-api-client/blob/b91d78b53fdc3a05b3c1d1e7fe0fd6b8cfc0dd17/src/std/rpc/ws_client/mod.rs#L60).

The cool thing is, some `no_std` libraries provide their own networking abstractions, like we have it in SGX. Hence, it is already a very useful thing to provide everything in `no_std` except the ws-client.

As the main part is already generic over the the traits above, we should be able to make almost everything `no_std` compatible by now.

**Comment by haerdib** [comment]
I have looked into it a little. Making the api-client no_std compatible is not that much work at all, if one leaves out the ws-client. If #267 is done, I think most of it should be solved already. If one leaves out the ws-client.

Regarding the ws-client:
I haven't found anything (once again) that is no_std even nearly `no_std` compatible. [tungstenite](https://github.com/snapview/tungstenite-rs) seems to be a fairly simple one, so one could look into that to see how much needs to done to make it `no_std` compatible. Maybe even a from scratch implementation is necessary. But what's certain: a `no_std` client will need to be fairly simple and slow. No async, no multithreading, no mio. And a lot of work. Not sure if that's worth it. Maybe a fire-and-forget client is somewhat more reasonable.

**Comment by clangenb** [comment]
Networking does usually need the very low-level primitives that interface with the hardware. I don't actually expect a generic `no_std` websocket client to be available at all. It is much more likely that the `ws_client` will be supplied by the user of the library, like our sgx compatible one, or one that is supplied by a browser lib.
