### ISSUE TITLE
Remove `ed25519-zebra` patch when possible

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#286]
The patch is necessary because the version used by substrate introduces std leaks in `no_std` when the `full_crypto` feature is enabled (which we do).

* Upstream issue: https://github.com/paritytech/substrate/issues/12225

**Comment by haerdib** [comment]
Has been merged: https://github.com/paritytech/substrate/commit/c4d36065764ee23aeb3ccd181c4b6ecea8d2447a

but is not yet in a polkadot release (release v0.9.31 does not contain the commit)

**Comment by haerdib** [comment]
polkadot-v0.9.33 finally does contain it (v0.9.32 not)
