### ISSUE TITLE
Document breaking changes

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#314]
Currently, there is no documentation or change log that makes any breaking changes from one commit to another visible.

To fix this I'm proposing the following:
- Add a tagging scheme according to the polkadot verison (because the api-client is following the substrate releases already with branches, adding a tag would not cause much additional effort).
- Similar to the worker, CI could create a release log that emphasizes the label `E1-breaksapi`. 

As this would probably affect the work with the worker, what do you think about that @clangenb @OverOrion ?

**Comment by haerdib** [comment]
1. I'd tag master, as the branches are stable and will not be updated once released.. so tags don't add additional information for branches. For the master it would.
2. We've not yet worked with versioning. Nor does substrate. So I'd propose to keep doing the releases according to the polkadot version, without any tags. Or what would the versioning be for?

**Comment by clangenb** [comment]
I think we don't need to adhere to substrate versioning here, just use regular semantic versioning, i.e.,

Pre v1: 
* breaking change → increase minor version
* New features → increase minor version.
* Small stuff -> increase patch version

Post v1.
*  breaking change → increase major version
*  new backwards-compatible features → increase minor version.
* only small stuff → increase patch version.

**Comment by haerdib** [comment]
Alright. I'll try to introduce that. Let's see how it will work :)

**Comment by clangenb** [comment]
Yes, master branch is fine with me 👍

**Comment by haerdib** [comment]
Closed by #323 . Tag will be incoming :)

**Comment by haerdib** [comment]
https://github.com/scs/substrate-api-client/releases/tag/v0.7.0 🥳
