### ISSUE TITLE
Jenkins: test_no_std and remaining examples

### ISSUE THREAD

**Issue by electronix** [scs/substrate-api-client#33]
Active the remaining items from #25 in Jenkins once they are fixed.

**Comment by brenzi** [comment]
Jenkins currently doesn't build pull requests. I think we should enforce that only PR's which build successfully may be merged into master. But that needs jenking to build PR's automatically

**Comment by electronix** [comment]
- Remaining examples are integrated into Jenkins and expected to timeout -> this needs fixing anyhow.
- test_no_std also working and integrated in Jenkins (can fail without setting the status to failure).
- Jenkins now also builds PRs (currently only tested for substrate-test-nodes and substrate-api-client)
