### ISSUE TITLE
failed to select a version for the requirement `sp-core = "^6.0.0"`

### ISSUE THREAD

**Issue by shanithkk** [scs/substrate-api-client#338]
error: failed to select a version for the requirement `sp-core = "^6.0.0"`
candidate versions found which didn't match: 7.0.0
location searched: Git repository https://github.com/paritytech/substrate.git?branch=master
required by package `substrate-api-client v0.7.0 (https://github.com/scs/substrate-api-client.git#b7f07a4e)`

**Comment by jlvihv** [comment]
I have also encountered this problem, does anyone have a solution?

**Comment by clangenb** [comment]
master needs to be updated to fix that. Alternatively, you can use one of the release branches here, like https://github.com/scs/substrate-api-client/tree/polkadot-v0.9.29.

**Comment by haerdib** [comment]
I think that should be fixable by removing the version number completely. AFAIK that was only introduced because of the `-dev` version from substrate which required the explicit version tagging.

**Comment by clangenb** [comment]
Yes, this is true, we can remove that.
