### ISSUE TITLE
support storage keys for double_map

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#34]
Currently, we don't directly support double_map storage queries

The following function should support `double_map`
https://github.com/scs/substrate-api-client/blob/3f8dc6011397aad1f856a0b0025db7dc66007562/src/utils.rs#L24

Which is defined as 
```
  blake256hash(bytes("ModuleName" + " " + "StorageItem") + bytes(scale("FirstStorageItemKey"))) + blake256hash(bytes(scale("SecondStorageItemKey")))
```
See: https://www.shawntabrizi.com/substrate/querying-substrate-storage-via-rpc/

**Comment by clangenb** [comment]
closed with #37
