### ISSUE TITLE
Error while building WASM

### ISSUE THREAD

**Issue by shanithkk** [scs/substrate-api-client#342]
error: failed to run custom build command for `wasmtime-runtime v1.0.2`

Caused by:
  process didn't exit successfully: `.../target/release/build/wasmtime-runtime-a2af9b306a3557ed/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=src/helpers.c
  TARGET = Some("wasm32-wasi")
  OPT_LEVEL = Some("3")
  HOST = Some("aarch64-apple-darwin")
  cargo:rerun-if-env-changed=CC_wasm32-wasi
  CC_wasm32-wasi = None
  cargo:rerun-if-env-changed=CC_wasm32_wasi
  CC_wasm32_wasi = None
  cargo:rerun-if-env-changed=TARGET_CC
  TARGET_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32-wasi
  CFLAGS_wasm32-wasi = None
  cargo:rerun-if-env-changed=CFLAGS_wasm32_wasi
  CFLAGS_wasm32_wasi = None
  cargo:rerun-if-env-changed=TARGET_CFLAGS
  TARGET_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  running: "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-wasi" "-Wall" "-Wextra" "-DCFG_TARGET_OS_wasi" "-DCFG_TARGET_ARCH_wasm32" "-o" "/Users/shanithkk/Hugobyte/work/macos/polkadot/bugs/testing/target/wasm32-wasi/release/build/wasmtime-runtime-2470cf0495410b55/out/src/helpers.o" "-c" "src/helpers.c"
  cargo:warning=src/helpers.c:1:10: fatal error: 'setjmp.h' file not found
  cargo:warning=#include <setjmp.h>
  cargo:warning=         ^~~~~~~~~~
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr

  error occurred: Command "clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=wasm32-wasi" "-Wall" "-Wextra" "-DCFG_TARGET_OS_wasi" "-DCFG_TARGET_ARCH_wasm32" "-o" "/Users/shanithkk/Hugobyte/work/macos/polkadot/bugs/testing/target/wasm32-wasi/release/build/wasmtime-runtime-2470cf0495410b55/out/src/helpers.o" "-c" "src/helpers.c" with args "clang" did not execute successfully (status code exit status: 1).

**Comment by clangenb** [comment]
Are you getting this error while building normally, or are you trying to build wasm? This crate does unfortunately not support wasm yet.

**Comment by shanithkk** [comment]
While trying to build in wasm,

**Comment by haerdib** [comment]
There have been quite a few updates recently. Which version of the api client has worked for you, and since when does it not work any more? That would help to locate the problem.

**Comment by shanithkk** [comment]
Okay thank you for your update. i will revert for now for time being.
