### ISSUE TITLE
Investigate: can the tip type be detected via metadata or Runtime?

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#344]
Currently, it has to be manually chosen which type of tips are used in the runtime (AssetTip, PlainTip). That's a hassle. Shouldn't it be possible to determine that via the metadata?

**Comment by haerdib** [comment]
Or maybe via Runtime (via PR #340) as Rust does not like type determination during runtime.

**Comment by haerdib** [comment]
Related issue : https://github.com/paritytech/substrate/issues/12929

**Comment by haerdib** [comment]
Via metadata (V14) it can be detected if the `pallet_asset_tx_payment` is imported into the runtime. And I believe, with quite some certainty, one can say if that's the case, then the fees will be paid with that pallet and so will the tips be. But I guess that not 100% sure, because one could simply define that pallet but not use it at all. 
This might be better once V15 is published.

**Comment by clangenb** [comment]
You can't because encointer does not use the `pallet_asset_tx_payment`, but we use `CommunityIdentifier` as asset id, which is not exposed in the metadata AFAIK.

**Comment by haerdib** [comment]
Metadata v15 is released, so this might not be blocked anymore.

**Comment by haerdib** [comment]
I've looked into it once again and came to the following conclusion: Yes, it would be possible to detect the tip during runtime with the metadata, but that would complicate a lot of things:
- Type safety: To allow generic tips, without allocating the tip type during compilation time, we would need to remove tip safety during compilation.
- While we can detect the "standard" tips according to their identifiers (`ChargeTransactionPayment`, `ChargeAssetTxPayment`, ..), I don't see how we can do that with self defined pallet tips (as long as the order of the SignedExtra is not fixed, which it is not AFAIK). So users having their own tip-pallet would have to set something before compilation, either way.

So long it's not a pressing user issue which has actual use cases, I don't see enough benefit on setting the Tip during runtime.
What we could easily do however is to check the set config against the metadata and if there's a mismatch we can print an error or warning.

**Comment by haerdib** [comment]
@masapr what do you think?

**Comment by clangenb** [comment]
At some point, there might be some relevant information in this issue: https://github.com/leonardocustodio/polkadart/issues/359

**Comment by masapr** [comment]
> @masapr what do you think?
I agree. It sounds like too much of a hassle.

@haerdib have you checked @clangenb's comment? Is this of any help?

**Comment by haerdib** [comment]
According to my understanding, they solve the problem by adding the extra input `customSignedExtensions` which may be the assetId or something else:
```dart
    final payloadWithCustomSignedExtension = SigningPayload(
      method: encodedCall,
      specVersion: specVersion,
      transactionVersion: transactionVersion,
      genesisHash: genesisHash,
      blockHash: blockHash,
      blockNumber: blockNumber,
      eraPeriod: 64,
      nonce: 0, // Supposing it is this wallet first transaction
      tip: 0,
      customSignedExtensions: <String, dynamic>{
        'PrevalidateAttests': 0, // A custom Signed Extensions
      },
    );
```
I'm not sure if that's easier than adapting the `Config`. However, it might be an extension possibility: Add a dynamic signing option for the users. Not sure about the use case though, as long as there's no cli. What I also like is the dynamic setting of the additional signed - not like our hardcoded part here: https://github.com/scs/substrate-api-client/blob/839ba6f0c8fcda0efc0733f635056a91b6df4355/primitives/src/extrinsics/extrinsic_params.rs#L58

I believe we could start by adding sensible runtime checks against the metadata and print warnings if there's a mismatch. That way, the users will know what to adapt without first investigating some strange runtime errors.

**Comment by masapr** [comment]
Yes, I think giving good warnings is probably the best in this case. Before we make it too complicated.

**Comment by haerdib** [comment]
Closing this issue in favour of the two follow-up issues #730 and #731. Please reopen if you disagree.
