### ISSUE TITLE
Introduce easy runtime updates (loop?)

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#348]
Since https://github.com/scs/substrate-api-client/pull/337 it's possible to update the runtime version and metadata. However, that currently needs to be done manually by the user. The way I'd imagine it, is that one listens to runtime upgrade events and then calls the `update_runtime` function.

This could be offered as a subscription function by the client itself, such that not every user needs to self-implement this.

Open question: Since we'd introduce mulithreading here, is a lock required? If so, is that possible in a no_std environment?

**Comment by Niederb** [comment]
Hmm, I think finding a nice solution to the locking issue is the main challenge. Some thoughts:
- We could build a separate `RuntimeUpdateSubscriber` which would take a `Mutex<Api<..>>`. Creating the `Mutex` is the responsibility of the user. Not very nice from a user perspective.
- The thread could just set an atomic bool (part of core) something like `needs_runtime_upgrade`. Then all the other functions would have to check the flag before doing anything. Not very nice, but I think this should work without `Mutex`
- `async` support could probably provide a nicer solution

**Comment by masapr** [comment]
so, let's first do the `async` support and then we look at this issue again? -> I adjusted the order in our backlog.

This feature is something, that has been asked for (see the comment by Paradox at [our Kusama proposal](https://kusama.subsquare.io/referenda/referendum/88)), so it would be good to implement it within this proposal.

**Comment by Niederb** [comment]
Closed by #635
