### ISSUE TITLE
Don't require `Pair` and `ExtrinsicParams` trait bound for getter implementations.

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#357]
We always require `Pair` or `ExtrinsicsParams` for all the `Api` implementations. This leads to the weird situation, where an actual pair needs to be supplied even if we never set a signer, as we don't need to sign anything, e.g.:

https://github.com/scs/substrate-api-client/blob/7ff294c406f0c03cd13b08e59272f6a3c0675836/examples/get_blocks.rs#L31

If we remove the trait bound for all getters, we can instantiate the `Api` like this, which is much simpler:

```rust
let api =  Api::<(), _, ()>::new(client).unwrap()
```

**Comment by haerdib** [comment]
Jup jup,  you're right, my bad !

**Comment by haerdib** [comment]
The Pair problem should be solved with PR #356. The ExtrinsicParams will need to be solved in a separate PR

**Comment by haerdib** [comment]
If we separate, then I believe two are enough. The ExtrinsicSender needs to be able to `get` things as well. At least to know its nonce. Therefore, I'd vote for `GetterClient` and `FullApiClient`. Three would just complicate the matter.

Hm.. maybe yes to the Config struct. But maybe both make sense, as the GetterClient would be a lot simpler than the FullApiClient, not needing any node information at all. 

If it's alright with you, I'll create a follow-up issue with a `GetterClient` creation and close this one. The Config issue already exists.

**Comment by clangenb** [comment]
This is ok for me, however, my ideas were just a brainstorm, take it with a grain of salt.

**Comment by haerdib** [comment]
Don't worry. I was thinking about that as well. And I think subxt has a similar concept with offline and online client.
