### ISSUE TITLE
`send_extrinsic` sometimes stuck while the extrinsic actually goes through 

### ISSUE THREAD

**Issue by Kailai-Wang** [scs/substrate-api-client#361]
I'm not sure if this is the right place for this issue, my apologies if not.

I met this problem when trying to implement a [litentry issue](https://github.com/litentry/litentry-parachain/issues/1061), so theoretically our parachain node should work exactly the same as a normal substrate node (except we still use aura for consensus, [PR here](https://github.com/litentry/litentry-parachain/pull/1066) if interested).

When starting the tee-worker and registering the enclave, `send_extrinsic(xthex, XtStatus::Finalized)` **sometimes** gets stuck (never returns) while the extrinsic already gets included in the block and executed -- I can even see the `AddedEnclave` event, the block detail in polkadot-js also shows the extrinsic is executed successfully:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/7630809/206310863-3b6c50df-e85d-4fe9-8586-f9a2601946bf.png">

<img width="1563" alt="image" src="https://user-images.githubusercontent.com/7630809/206310830-5f150f0a-ea47-4e34-a7dc-59311b8e7260.png">

Maybe you've got a quick idea of what happens here? Or anything I can do to narrow down the problem?
It's not necessarily a problem inside `substrate-api-client`, maybe the standalone node is missing something/wrongly configured, as the full parachain works (relaychain + parachain network).

Please also note it happens sometimes, not always.

**Comment by haerdib** [comment]
"Sometimes" meaning sometimes with the very same node or sometimes with different settings? The first thing coming to mind is that the no blocks are finalized in the substrate node.

**Comment by Kailai-Wang** [comment]
Same node, same settings.

> no blocks are finalized in the substrate node.
That can'be the case :( I can see in polkadot-js app that blocks are being produced, and as mentioned I can look into the block and see the extrinsic `registerEncalve` was executed successfully, together with the event.

Can this be related to the finalisation mechanism that the substrate node uses? We are using aura and an [instant finalisation](https://github.com/litentry/litentry-parachain/blob/96cfd2bd940e043bbc3ec5313c4d08e6acb3a176/node/src/standalone_block_import.rs) method.

**Comment by Kailai-Wang** [comment]
find this: https://github.com/PureStake/moonbeam/pull/1012

**Comment by haerdib** [comment]
I don't really get the root problem there. But the api-client does rely on TransactionStatus updates. So if a finalized update is somehow missed (or not even issued), it will wait for finalization forever. I don't see what we could do on the client side except for:
- Only wait for `InBlock`
- Introduce a reasonable timeout once `jsonrpsee` has been introduced as rpc client (supports timeouts: https://github.com/paritytech/jsonrpsee/blob/3a159638ed6c8ad4c80ad80bea74ef1d13f2f503/core/src/client/async_client/mod.rs#L98-L103)
There's already an open PR for this: https://github.com/scs/substrate-api-client/pull/351 so it will be available soon.
