### ISSUE TITLE
how do I link the contract?

### ISSUE THREAD

**Issue by CoderfishGzh** [scs/substrate-api-client#362]
What do I need to do to call the functions inside the ink!contract deployed on substrate. The example given in the documentation seems to be the only way to deploy the contract, so how do I link the contract?

**Comment by haerdib** [comment]
With the function 

https://github.com/scs/substrate-api-client/blob/d540964c2891ba8033a88a91337886bccf7bb58c/src/extrinsic/contracts.rs#L132-L148

you can create a substrate `call` extrinsic, which refers to this function in the pallet: https://github.com/paritytech/substrate/blob/master/frame/contracts/src/lib.rs#L550-L594.

The contract address you can retrieve from the Instantiated Event, check out the later part of the example:

https://github.com/scs/substrate-api-client/blob/d540964c2891ba8033a88a91337886bccf7bb58c/examples/contract_instantiate_with_code.rs#L75-L79

I hope that answers your question.

**Comment by haerdib** [comment]
Closing this as answered. Please re-open in case there's still a problem.
