### ISSUE TITLE
generic compose_extrinsic() function

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#4]
The current version of this library can't compose extrinsics for custom runtimes because there's a dependency clash between custom `node_runtime` and substrate master `node_runtime`.

This should be solvable along these lines:
* not depending on substrate's node_runtime crate with api-client
* using type arguments, so a depending crate can supply the custom node_runtime dependencies 

in addition to generic extrinsics, we should provide very common extrinsic types with easy function calls, probably wrapping the dispatch of the call as well:
* transfer() as in [extrinsics.rs](https://github.com/scs/substrate-api-client/blob/61bc5233582952a9ff13ab24fb93b08396758bf1/src/examples/extrinsic/mod.rs#L175)
* ink contract handling #5 
* upgrade chain runtime as in [Gav's Demo](https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain#step-5-upgrade-our-chain)

write an example for how to compose an extrinsic for a custom runtime module using Gav's Demo:
https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain#step-6-interacting-with-our-new-module

**Comment by clangenb** [comment]
as well offer the option to use Sr25519 or Ed25519 keys

**Comment by clangenb** [comment]
Upgrade chain runtime has not been integrated. Rest has been implemented
