### ISSUE TITLE
Clean up trait bounds

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#406]
As @clangenb  wrote in https://github.com/scs/substrate-api-client/pull/398#discussion_r1059920566 : 
> I see us repeatedly having these excessive trait bounds. I would vote for adding them to the respective pallet's config, so we don't need to repeat them here every time.

**Comment by haerdib** [comment]
Maybe something like that: https://github.com/paritytech/subxt/blob/92ace0629a63fadeebd428c5b1356ba60eeabfeb/subxt/src/config.rs

**Comment by clangenb** [comment]
I like their approach

**Comment by haerdib** [comment]
Keep in mind: https://github.com/paritytech/substrate/issues/12939. This might prove quite relevant for this issue as well. Defining "by default " parameters is not very dummy proof and will most likely cause issues in the future. With metadata V15, several of these types might be retrievable via metadata.
