### ISSUE TITLE
Remove or rework hanging examples

### ISSUE THREAD

**Issue by electronix** [scs/substrate-api-client#41]
The examples
- contract and
- event_callback
dont' terminate and cannot be automatically testet.

Proposal: 
- Introduce an option in example_event_callback to only listen to a certain number of events and then terminate
- Fix or remove the example_contract

**Comment by electronix** [comment]
`example_compose_extrinsic_offline` also runs into a time-out and need to be reworked/removed

**Comment by clangenb** [comment]
* example_contract is fixed
