### ISSUE TITLE
upstream update to get full_crypto PR #3778

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#42]
Since https://github.com/paritytech/substrate/commit/cefe4dc2ee4a1ed27fb171bdf65aed81ba0da44a we have a new feature `full_crypto` in substrate-primitives and application-crypto which allows us to drop our own forks.

**Comment by brenzi** [comment]
see also https://github.com/scs/substraTEE-worker/issues/65

**Comment by clangenb** [comment]
Done in #46
