### ISSUE TITLE
`substrate_api_client::api::api_client::Api::new` fails to establish connection in `async` context

### ISSUE THREAD

**Issue by michaelassaf** [scs/substrate-api-client#442]
The method `substrate_api_client::api::api_client::Api::new` fails to establish a new API client. It hangs and fails with the following error when executed in an `async` context.
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: RpcClient(Client(RequestTimeout))'
```
When I remove `async` from the function, the client establishes a connection.

Here is the code (I have isolated and determined that the error does indeed stem from the function being `async`)
```rust
#[tauri::command]
async fn create_account<'a>(
    name: &str,
    session: State<'a, Session>,
) -> Result<(String, String, String), String> {
    let derived_key = session.derived_key.read().await;

    Secret::<[u8; 32]>::random(|password| {
        let password = password.as_bytes();
        let password = hex::encode(password);

        let account = keystore::add_keypair(name, &password, &*derived_key).unwrap();

        println!("account: {:?}", account);

        // create account on chain
        let client = JsonrpseeClient::with_default_url().unwrap();
        let alice_signer = AccountKeyring::Alice.pair();
        let mut api =
            Api::<_, _, PlainTipExtrinsicParams<KitchensinkRuntime>, KitchensinkRuntime>::new(
                client,
            )
            .unwrap();
        api.set_signer(ExtrinsicSigner::<_, Signature, KitchensinkRuntime>::new(
            alice_signer.clone(),
        ));

        let (free, reserved) = init_balances();

        let address = account.address.to_ss58check();
        let multi_addr = keystore::get_signer_multi_addr(account.address);

        let xt = compose_extrinsic!(
            &api,
            "Balances",
            "set_balance",
            Box::new(&multi_addr),
            Box::new(free.clone()),
            Box::new(reserved.clone())
        );

        let xt_hash = api
            .submit_and_watch_extrinsic_until(xt, XtStatus::InBlock)
            .unwrap();
        println!("[+] Extrinsic hash: {:?}", xt_hash);

        // Get the nonce of the signer account (online).
        let signer_nonce = api.get_nonce().unwrap();
        println!("[+] {}'s Account Nonce is {}\n", name, signer_nonce);

        let last_finalized_header_hash = api.get_finalized_head().unwrap().unwrap();
        let header = api
            .get_header(Some(last_finalized_header_hash))
            .unwrap()
            .unwrap();
        let period = 5;
        let tx_params = GenericAdditionalParams::new()
            .era(
                Era::mortal(period, header.number.into()),
                last_finalized_header_hash,
            )
            .tip(0);
        api.set_additional_params(tx_params);

        // Compose the extrinsic (offline).
        let call = RuntimeCall::Balances(BalancesCall::transfer {
            dest: multi_addr,
            value: 500,
        });
        let xt = api.compose_extrinsic_offline(call, signer_nonce);

        // Send and watch extrinsic until in block (online).
        let block_hash = api
            .submit_and_watch_extrinsic_until(xt, XtStatus::InBlock)
            .unwrap()
            .block_hash
            .unwrap();
        println!("[+] Extrinsic got included in block {:?}", block_hash);

        let address = format!("{:?}", address);
        Ok((account.password, address, account.mnemonic))
    })
}
```

**Comment by michaelassaf** [comment]
I made it work using `let client = WsRpcClient::new("ws://127.0.0.1:9944").unwrap();` to create the client instead of using `let client = JsonrpseeClient::with_default_url().unwrap();`. How could I debug this further?

**Comment by haerdib** [comment]
The difference lies with tokio - the jsonrpsee client uses async `tokio` as runtime (see https://github.com/paritytech/jsonrpsee/blob/master/client/ws-client/src/lib.rs#L27-L33), and therefore needs to be run in an async environment.

As comparison:

See the example of ws client: https://github.com/scs/substrate-api-client/blob/7dd79e40853fa2ab3a0458a8b799345f6b8a3665/examples/examples/transfer_with_ws_client.rs#L28-L30

Example with a jsonrpsee client: https://github.com/scs/substrate-api-client/blob/7dd79e40853fa2ab3a0458a8b799345f6b8a3665/examples/examples/event_callback.rs#L27-L29

I don't know why it's a problem that the connection is happening inside an async function, even though tokio is designed for async. Regretfully, I don't yet have much experience with tokio, we've only just started using it. So I'd need to investigate further there.

As a quick fix for your problem, however, I'd advise you to create the `Api` once at initialization of your project and pass it as an argument into your async function. This way, you can submit multiple extrinsic, without having to re-establish a connection each time.
Like it's done here (without async though): https://github.com/scs/substrate-api-client/blob/7dd79e40853fa2ab3a0458a8b799345f6b8a3665/examples/examples/staking_batch_payout.rs#L140-L149

I believe that should work.

**Comment by masapr** [comment]
@michaelassaf can we close this issue?
As I understand, you found a solution. As @haerdib wrote: the jsonrpsee client needs tokio to run, so I think that's the reason to the error.

**Comment by masapr** [comment]
Due to no reply, I'll close this issue. Feel free to open it again, if there is still an issue.
