### ISSUE TITLE
Redefinition of substrate types can lead to cumbersome errors

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#450]
There are some types redefined to get `no-std` deserialization, however this can lead to the following errors, which might be hard to resolve:

![image](https://user-images.githubusercontent.com/37865735/217916238-ab2addfb-cfe2-4973-a285-2ecc6467d6ab.png)

We should check if the `no-std` deserialization can be upstreamed.

**Comment by haerdib** [comment]
Yeah. There's an open PR on substrate, didn't get a response for quite some time. Not sure what else I can do. 

See https://github.com/scs/substrate-api-client/issues/391 for more info.

**Comment by haerdib** [comment]
Closing this as duplicate. Please reopen if you disagree.
