### ISSUE TITLE
impl sp_core::crypto::Pair for ExtrinsicSigner

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#453]
Makes it much easier to use the extrinsic signer in all the substrate codebases.

**Comment by masapr** [comment]
I'm not sure we should use the ExtrinsicSigner as if it was a signer ... in the end it still has a reference to a real signer, that already implements this trait. So why not use this signer in those cases? ... implementing this is a lot of boiler plate code. I'm currently thinking we should rather rethink, if adding the ExtrinsicSigner was such a good idea in the first place. Or if it is, maybe we should not misuse it as a real "signer" (a different name could be good in this case).
