### ISSUE TITLE
Remove `Params: ExtrinsicParams<Runtime::Index, Runtime::Hash>,` for GetHeader trait

### ISSUE THREAD

**Issue by clangenb** [scs/substrate-api-client#457]
Also for `GetAccountInformation`

**Comment by haerdib** [comment]
Not so easy. See discussion in https://github.com/scs/substrate-api-client/issues/357. The solution will be https://github.com/scs/substrate-api-client/issues/432

**Comment by haerdib** [comment]
Closing this as duplicate. Please reopen if you disagree.
