### ISSUE TITLE
Introduce a no-wasm compatible `ExtrinsicSigner`

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#461]
The current `ExtrinsicSigner` depends on a `Runtime`. But the node Runtime is not available in an environment where wasm is not supported.

Therefore, a No wasm compatible `ExtrinsicSigner` (implementing the same trait `SignExtrinsic`) where no Runtime type input is needed could be introduced.

If not possible in any other way, a hardcoded extrinsic_address type conversion may be used.

@clangenb Would that help your usecase?

**Comment by haerdib** [comment]
Answering myself: yes, definitely. Necessary for signing extrinsic in the TEE.

**Comment by clangenb** [comment]
We can use the runtime inside the TEE. We do this already. :)

**Comment by clangenb** [comment]
Ah wait, this is only the sgx runtime. :P

**Comment by haerdib** [comment]
Hah. I just panicked for a short moment here. Was already double checking 😨

**Comment by haerdib** [comment]
But anyway: For simply signing extrinsics, importing the full Runtime is not worth it. So it's useful anyway
