### ISSUE TITLE
Create Polkadot branch v0.9.39

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#475]
New releases are available, so we should follow

Update to new polkadot branch v0.9.39

- [x] create new branch `polkadot-v0.9.39`: based on tag `v0.10.0`
- [x] create new branch `polkadot-v0.9.39-tag-v0.9.0`: based on tag `v0.9.0
- [x] create new branch `polkadot-v0.9.39-tag-v0.7.0`: based on tag `v0.7.0`

**Comment by echevrier** [comment]
- Upgrade branch polkadot-v0.9.38-tag-v0.10.0, based on tag v0.10.0, to **polkadot v0.9.39**: see https://github.com/scs/substrate-api-client/pull/489
- Upgrade from branch polkadot-v0.9.38 to **polkadot-v0.9.39-tag-v0.0.9** : https://github.com/scs/substrate-api-client/pull/482
- Upgrade from branch polkadot-v0.9.38-tag-v0.0.7 to polkadot-v0.9.39-tag-v0.0.7: https://github.com/scs/substrate-api-client/pull/490
