### ISSUE TITLE
Run examples with panick

### ISSUE THREAD

**Issue by cezhang52111** [scs/substrate-api-client#49]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("Error decoding field RuntimeMetadataPrefixed.1")', src/libcore/result.rs:1192:5

**Comment by clangenb** [comment]
I would say that this is most likely due to an incompatible node. Do the api-client's and the node's substrate version match?

**Comment by cezhang52111** [comment]
Sorry, I use the latest version of the node-template. I think the reason is that they are incompatible.

**Comment by clangenb** [comment]
No worries, in that case you can use #51 . It is works with https://github.com/paritytech/substrate/commit/00a400f82539e2f78e8ddbcd98aea512c87c5f3c and is going to be merged into master soon.
