### ISSUE TITLE
Enhance readability of submit_and_watch_extrinsic_until_success

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#491]
Currenlty `submit_and_watch_extrinsic_until_success` expects a boolean for `Finalized` or `InBlock`. That's not very user-friendly.

We could either:
- Introduce an Enum with Enum::InBlockSuccess or Enum::FinalizedSuccess (something like that)
- Introduce two functions, one for finalized and one for InBlock.

**Comment by echevrier** [comment]
This is closed by https://github.com/scs/substrate-api-client/pull/606
A new function `submit_and_watch_extrinsic_until` replaces `submit_and_watch_extrinsic_until_success`. This function accepts any of the statuses, not just Finalized or InBlock.  See: https://github.com/scs/substrate-api-client/blob/58083b637db252fefc4db5f6e397c0c60d0078e3/src/api/rpc_api/author.rs#L107
