### ISSUE TITLE
Introduce account getter helpers

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#495]
E.g. `get_nonce_of` and `get_free_balance`. I think these are standard functionalities and should be offered by the api-client.

See worker implementation: https://github.com/integritee-network/worker/blob/master/core-primitives/node-api/api-client-extensions/src/account.rs

**Comment by Niederb** [comment]
I volunteer to do this as I think this would be a good issue for me to deepen my understanding of the api-client

**Comment by haerdib** [comment]
Sound good. But now that I think about it: `get_free_balance` might not be possible  to implement (yet). The problem: The generic `AccountData` Type (given by the frame-system pallet) does not know about its `free` type.

**Comment by Niederb** [comment]
@haerdib As you said I don't think it is possible to get the free balance from AccountData currently. So this is half done. Should we close or keep it open?

**Comment by haerdib** [comment]
I'd vote for closing this for now. It's not a necessary feature anyway.
