### ISSUE TITLE
get block api

### ISSUE THREAD

**Issue by alanpoon** [scs/substrate-api-client#50]
'''rust
pub fn chain_get_block(hash:String) -> Value {
    json!({
    "method": "chain_getBlock",
    "params": [hash],
    "jsonrpc": "2.0",
    "id":"1"
    })
}
'''
Any support for rpc chain_getBlock?

**Comment by brenzi** [comment]
Sounds reasonable. We're happy to take a PR ;-)

**Comment by brenzi** [comment]
I included these changes in branch `v2.0.0-alpha.5`

**Comment by brenzi** [comment]
done in #66
