### ISSUE TITLE
Support Runtime Api calls

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#520]
So far the api-client does not support runtime api calls. The goal of this issue is to facilitate runtime api calls, in general, and provide helper functions for the runtime api calls of the most commonly used pallets.

Available Runtime Calls: https://polkadot.js.org/docs/polkadot/runtime

Hands on testing: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.dotters.network%2Fkusama#/runtime

Subxt has already put some thoughts into it: see https://github.com/paritytech/subxt/pull/918

### Task description
Implement helper functions, just like our rpc calls 
https://github.com/scs/substrate-api-client/blob/53be73d9faf72ba492cb3af9a163f2e26d2f8619/src/api/rpc_api/frame_system.rs#L73-L81

that directly access the node api and return the information. 

Example code from subxt:
```rust
// Create a dynamically runtime API payload that calls the
// `AccountNonceApi_account_nonce` function.
let account = dev::alice().public_key();
let runtime_api_call = subxt::dynamic::runtime_api_call(
    "AccountNonceApi",
    "account_nonce",
    vec![Value::from_bytes(account)],
);
```

And as reference: here's the call executed by the rpc: https://github.com/paritytech/subxt/blob/9a8fc33f2fe830009011e997773071099101d69b/subxt/src/runtime_api/runtime_types.rs#L43-L106

### Already implemented:
- Support for Metadata v15
- Api Metadata (maybe needs adaption)
https://github.com/scs/substrate-api-client/blob/53be73d9faf72ba492cb3af9a163f2e26d2f8619/node-api/src/metadata/metadata_types.rs#L48

**Comment by haerdib** [comment]
I'm not yet sure if it makes sense to do this, as we need a node running with v15 to test it. But on the other hand, we should be ready with it, once v15 is out in the wild. So I'd start with this task, but maybe not fully release it, but instead just do the necessary preparatory work.

**Comment by haerdib** [comment]
Up to date Substrate nodes should already include metadata v15 by default. So this feature should (once the Susbtrate deps are upgraded) already be testable by CI (see PR https://github.com/paritytech/substrate/pull/14481 for more information)

**Comment by masapr** [comment]
To me it's not clear: do we implement all calls manually? Or do we generate code? If we generate code automatically, do we do this frequently/whenever there are changes in the runtime api call?

**Comment by haerdib** [comment]
Currently, we are not generating code at all in the api-client. So for now, I'd stick to hard coded helper functions and one function that allows a generic "String" input... or Probably two Strings, as in polkadot.js:
![grafik](https://github.com/scs/substrate-api-client/assets/73821294/d5e6f1d8-6ba1-47a7-958e-d406770c605a)

If we want to go more in the direction of code producing code, I believe that should be addressed in a different issue, as it also affects the already implemented RPC calls.
