### ISSUE TITLE
How to perform `set_storage` that stores key:values in the substrate chain?

### ISSUE THREAD

**Issue by kebab-mai-haddi** [scs/substrate-api-client#57]
Like we have [`get_storage`](https://github.com/scs/substrate-api-client/blob/master/src/lib.rs#L222), we should also have `set_storage` that would take the name of the key-value map(say, `file_ownership`) and store key-values in it. 

I am assuming that this storage would be defined in the logic of the Substrate chain itself?

**Comment by kebab-mai-haddi** [comment]
CC: @brenzi  @clangenb 

Guys, if need be, I will voluntarily contribute to this feature.

**Comment by brenzi** [comment]
This is not how you should do it. We will never write to storage directly. You have to write your own pallet module that exposes a setter. Only extrinsics can change storage. Please visit substrate tutorials on how to do it
