### ISSUE TITLE
Failed to compile on #![feature(error_in_core)]

### ISSUE THREAD

**Issue by f-squirrel** [scs/substrate-api-client#581]
I added the crate as follows `substrate-api-client = "0.11.0"`.
When I compile, I receive the following error message:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /.cargo/registry/src/github.com-1ecc6299db9ec823/substrate-api-client-0.11.0/src/lib.rs:18:12
   |
18 | #![feature(error_in_core)]
   |            ^^^^^^^^^^^^^
```

Rust version: 1.68.2

Does it mean that the crate requires a nightly compiler version?
It is not mentioned anywhere in the documentation.

Is there any way to avoid this error?

**Comment by haerdib** [comment]
Hello @f-squirrel 

Yes, you currently need the nightly version. The rust version is specified in the [rust-toolchain.toml](https://github.com/scs/substrate-api-client/blob/master/rust-toolchain.toml) file. With the cli cmd `rustup show` the toolchain should be installed automatically.

Checkout this part of the Readme:  https://github.com/scs/substrate-api-client#prerequisites

**Comment by masapr** [comment]
We assume this is resolved. Feel free to reopen the issue if not.
