### ISSUE TITLE
How to read a Storage Map?

### ISSUE THREAD

**Issue by kebab-mai-haddi** [scs/substrate-api-client#59]
The APIs for plain storage values and for storage double maps are given but not for storage maps.
I tried the following but the hash generated for my value is different from what it should be.
What I tried:
```
fn file_storage_key_hash_vec(module: &str, storage_key_name: &str, param: &str) -> Vec<u8> {
    let mut key = twox_128(module.as_bytes()).to_vec();
    // println!("Keyhash after module hex encoding is: {:?}", key);

    key.extend(&twox_128(storage_key_name.as_bytes()));
    // println!("Key after storage encoding is: {:?}", key);

    key.extend(&blake2_256(param.as_bytes()));

    let module_encoding = hex::encode(&twox_128(module.as_bytes()));
    let storage_key_name_encoding = hex::encode(&twox_128(storage_key_name.as_bytes()));
    let file_hash_encoding = hex::encode(&blake2_256(param.as_bytes()));
    println!("------------------------------------------");
    println!("Module encoding: {:?}", module_encoding);
    println!("Storage Key Name encoding: {:?}", storage_key_name_encoding);
    println!("File Hash encoding: {:?}", file_hash_encoding);
    println!("------------------------------------------");
    

    println!(
        "IMPORTANT: key after file hash encoding of blake2_256 is: {:?}",
        key
    );
    key
}

```
For hash value: `0x0000000000000000000000000000000000000000000000000000000000000001`, the `file_hash_encoding` generated is `47016246ca22488cf19f5e2e274124494d272c69150c3db5f091c9306b6223fc`. 

The value that should be generated is:
```
0x33e423980c9b37d048bd5fadbd4a2aeb95146922045405accc2f468d0ef96988
```

The correct value generated is achieved by using the function `util_crypto.blake2AsHex("0x0000000000000000000000000000000000000000000000000000000000000001")` as taken from [here](https://stackoverflow.com/a/60782822/10834788)

So, how can I read the value given the aforementioned key?

**Comment by brenzi** [comment]
There is an example with storage map:
https://github.com/scs/substrate-api-client/blob/822b0fd7fe4df5dabdb3c60c75d12d36cccba2f2/src/examples/example_get_storage.rs#L46

**Comment by kebab-mai-haddi** [comment]
Got it.
Can you help me with hex encoding?

I am facing [this](https://stackoverflow.com/questions/60792643/how-to-achieve-blake2ashex-functionality-from-polkadot-js-in-substrate) problem here. While reading the hex values, I am not getting the correct hex generated and so, unable to read the storage map.

Complete working code is available [here](https://github.com/kebab-mai-haddi/substrate-api-client/blob/read-storage/src/examples/example_substratekitties.rs#L32) but I don't think you would need it as I am clearly missing some Rust fundamentals.

**Comment by brenzi** [comment]
You can use this: 
https://github.com/scs/substrate-api-client/blob/822b0fd7fe4df5dabdb3c60c75d12d36cccba2f2/src/utils.rs#L100

**Comment by kebab-mai-haddi** [comment]
Hey, I did it.
I need to decode the result into account id. that is it, can you help me with that?
This is what I did:
```
fn main() {
    env_logger::init();
    let url = get_node_url_from_cli();
    let mut api = Api::new(format!("ws://{}", url));
    let signer = AccountKeyring::Alice.pair();
    api.signer = Some(signer);

    // get some plain storage value
    // let file_key: Option<Vec<u8>> = Some("0x0000000000000000000000000000000000000000000000000000000000000001".as_bytes().to_vec());
    let file_hash = "0000000000000000000000000000000000000000000000000000000000000001";
    let result_str = api.get_file_storage("KittyStorage", "Value", file_hash).unwrap();
    println!("Result string is: {}", result_str);
    let result = hexstr_to_u256(result_str).unwrap();
    println!("The result is {}", result);

}
```
This is what I got:
```
Result string is: "0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d"
The result is 56826092060526977254125881710066122751479662717075902413552231940870613710292
```

What I want is to get the account id of Alice, which is:
```
5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
```

**Comment by brenzi** [comment]
have a look at this. IT's a `vec<AccountID>`, but I it shows how to do it
https://github.com/encointer/encointer-node/blob/be4055bcee18a509a347527263f4576787881153/client/src/main.rs#L665

**Comment by kebab-mai-haddi** [comment]
Hey @brenzi 
I tried looking at it but still could not implement it. I am still unable to get the account id.

I know the hex representation is right and I tried it in browser's console and got the correct id. I tried this in browser: `keyring.encodeAddress("0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d")`.

Now, what I need to do is get the account id from this hex string.
Can you help me with that?

Thanks in advance!
