### ISSUE TITLE
improve examples to check for extrinsic-success and report errors and events triggered by the extrinsic

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#591]
https://github.com/scs/substrate-api-client/blob/b884bf3de5c4e984b9c806ccdc96b9fe77cfdb91/examples/examples/transfer_with_ws_client.rs#L70
currently, the example just returns the tx hash. What I'd like to see is:
* did the extrinsic not only get included, but did it yield a extrinsicSuccess event?
* if not, report error
* if events were triggered by this extrinsic, return events

**Comment by haerdib** [comment]
`submit_and_watch_extrinsic_until` currently returns an `ExtrinsicReport`:

https://github.com/scs/substrate-api-client/blob/b884bf3de5c4e984b9c806ccdc96b9fe77cfdb91/src/api/mod.rs#L35-L50

So you can retrieve the `tx_hash`, as well as the last known status or Block hash (if watched long enough).

However, what you want is probably the following function:
https://github.com/scs/substrate-api-client/blob/b884bf3de5c4e984b9c806ccdc96b9fe77cfdb91/src/api/rpc_api/author.rs#L146-L165

Check out the example:
https://github.com/scs/substrate-api-client/blob/b884bf3de5c4e984b9c806ccdc96b9fe77cfdb91/examples/examples/event_error_details.rs#L65-L80

**Comment by haerdib** [comment]
But I agree: the example should be renamed - event_error_details is not appropriate anymore.

**Comment by haerdib** [comment]
The `transfer` examples are mainly to show the different ws clients and I'd like to avoid too many duplicate examples, so printing and checking everything there seems to be an overkill.

Proposing the following:
- change transfer examples ([transfer_with_ws_client.rs](https://github.com/scs/substrate-api-client) /blob/b884bf3de5c4e984b9c806ccdc96b9fe77cfdb91/examples/examples/transfer_with_ws_client.rs) and [transfer_with_ws_client.rs](https://github.com/scs/substrate-api-client/blob/b884bf3de5c4e984b9c806ccdc96b9fe77cfdb91/examples/examples/transfer_with_tungstenite_client.rs)
to use `until_success`. With `unwrap()` to ensure it has been successful, as this is probably the default use case.
- Rename `event_error_details.rs` to `check_for_failed_extrinisc.rs` (to be discussed, I suppose) and update the  `println!` msg.
- There's currently no example showing the full capacity for `ExtrinsicReport` (incl. the contained Events). That should be changed. TBD: Where to be included?

**Comment by pifragile** [comment]
@haerdib 
i am trying to get the events from a `tx_report`, as in
```
let tx_report = api.submit_and_watch_extrinsic_until(xt, XtStatus::InBlock).unwrap();
```

what is get is:
```
ExtrinsicReport { extrinsic_hash: 0xc22166d00cf41adab1cf066c681b7bc8eed1f1357a6b99232224e00150d51ad6, block_hash: Some(0x6fc9c0978d61ff5d87f346fa63798a55d25e47b148c8ac0253d86ec682f3283f), status: InBlock(0x6fc9c0978d61ff5d87f346fa63798a55d25e47b148c8ac0253d86ec682f3283f), events: None }
```

even though the extrinsic is successful and there are events issued with this extrinsic. how can i get the events back? do i have to set some extra flag or something?

**Comment by haerdib** [comment]
To retrieve the extrinsic with the report, please use the `submit_and_watch_extrinsic_until_success` function.
Check out this test here:
https://github.com/scs/substrate-api-client/blob/b884bf3de5c4e984b9c806ccdc96b9fe77cfdb91/testing/examples/author_tests.rs#L111-L146
