### ISSUE TITLE
write example with custom struct runtime storage

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#6]
Along the lines of 

https://substrate.dev/recipes/storage/structs.html
https://www.shawntabrizi.com/substrate-collectables-workshop/#/1/viewing-a-structure

* define some custom struct in runtime module storage (i.e. directly referencing cryptokitties tutorial and using that runtime)
* query struct storage from rust example

**Comment by kebab-mai-haddi** [comment]
What happened to this issue? Was this developed?

**Comment by brenzi** [comment]
https://github.com/scs/substrate-api-client/blob/master/src/examples/example_custom_storage_struct.rs

**Comment by vyorkin** [comment]
This file now has a `.DEPRECATED` extension for some reason. So I'm not sure if it works. I Is there any other example?

**Comment by clangenb** [comment]
It will probably not work as is, but minor adjustments should suffice to make it work. We dropped maintenance, as we'd also need to maintain a node with a runtime containing the CustomStruct.
