### ISSUE TITLE
Evaluate: Support Runtime API calls

### ISSUE THREAD

**Issue by masapr** [scs/substrate-api-client#609]
Evaluate what needs to be done for #520 and if we should add the task to our next work package

**Comment by haerdib** [comment]
I investigated a little and documented all my findings in #520. 

Regarding if we should add it to next proposal: Yes, definitely. Parity just recently stabilized metadata v15 in [frame-metadata v16.0.0](https://github.com/paritytech/frame-metadata/blob/main/frame-metadata/src/lib.rs#L75-L76
) and in [Substrate itself](https://github.com/paritytech/substrate/pull/14481/files)
