### ISSUE TITLE
Expected subscription, but received an id response instead

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#620]
`[2023-07-17T12:15:31Z WARN  substrate_api_client::rpc::ws_client] Expected subscription, but received an id response instead: Object {"id": String("1"), "jsonrpc": String("2.0"), "result": String("5mV2Ue1jpPJKhTBp")}`

I guess this has to do with recent update of behavior of the spi-client.
This happens when we do
`submit_and_watch_extrinsic_until`

using api client: polkadot-v0.9.42-tag-v0.10.0#686b7ef0aa8da255d3864a3fc703e32193813700
node is based on: polkadot-v0.9.42#569aae5341ea0c1d10426fa1ec13a36c0b64393b

it looks like the consequence of this warning is that the return value is "extrinsic failed" although it succeeded

**Comment by brenzi** [comment]
same warning already occurred on a previous dep:
https://github.com/scs/substrate-api-client.git?branch=polkadot-v0.9.39#d872c2ca4328a30222e4d470c8fc4921abad9f34

**Comment by brenzi** [comment]
steps to reproduce:

run integritee-node 1.0.36 (polkadot-0.9.42 deps)
```
wget https://github.com/integritee-network/integritee-node/releases/download/1.0.36/integritee-node-dev
chmod +x integritee-node-dev
./integritee-node-dev --dev 
```

run substrate api client example:
```
git checkout polkadot-v0.9.42-tag-v0.10.0
export RUST_LOG=warn
cargo run -p ac-examples --example transfer_with_ws_client
```
this will hang. a warning will be issued (because runtimes don't match), but actually it should terminate.

will try to build this example against our runtime now

**Comment by brenzi** [comment]
our real issue is #624

**Comment by haerdib** [comment]
Closing this for now. To my understanding, all issues are already tracked in other issues. Please reopen if that's not the case.
