### ISSUE TITLE
`DefaultRuntimeConfig` in ExtrinsicSigner::<..> does not work

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#628]
When initializing the Api with `DefaultRuntimeConfig` and a signer as following:
```rust
let mut api = Api::<DefaultRuntimeConfig, _>::new(client).unwrap();
api.set_signer(GenericExtrinsicSigner::<DefaultRuntimeConfig>::new(sudoer));
```

It does not compile due to:
```
note: expected struct `ExtrinsicSigner<AssetRuntimeConfig>`
   found struct `ExtrinsicSigner<WithExtrinsicParams<AssetRuntimeConfig, GenericExtrinsicParams<AssetRuntimeConfig, PlainTip<u128>>>>`
label: expected `ExtrinsicSigner<AssetRuntimeConfig>`, found `ExtrinsicSigner<WithExtrinsicParams<..., ...>>`
```

I suppose the error comes from the definition of `DefaultRuntimeConfig`:
```rust
/// Standard runtime config for Substrate and Polkadot nodes.
pub type DefaultRuntimeConfig =
	WithExtrinsicParams<AssetRuntimeConfig, PlainTipExtrinsicParams<AssetRuntimeConfig>>;
```

Workaround:
```rust
api.set_signer(GenericExtrinsicSigner::<_>::new(sudoer));
```
But that is still not nice. Isn't there a better way to define the `ExtrinsicSigner`?

**Comment by clangenb** [comment]
I have opted not to define any extrinsic signed in the worker, as you can simply do:

```rust
api.set_signer(sudoer.into());
```

What is your take on that?

**Comment by haerdib** [comment]
Perfect workaround and the way everybody will most likely do it. But it is still a workaround in the end, is it not? The compiler still expects a hardcoded `AssetRuntimeConfig` for `ExtrinsicSigner`. Currently, that's not a problem, but what happens if the user defines it own Config with entirely different parameters, that also affects the Signer? Might cause some problems.
