### ISSUE TITLE
Unable to write extrinsic

### ISSUE THREAD

**Issue by kebab-mai-haddi** [scs/substrate-api-client#63]
Getting "BadProof" and "InvalidTransaction" upon attempting to submit an extrinsic that writes value to a custom storage map in Substrate.

Full details: https://stackoverflow.com/questions/61005569/how-to-write-in-the-storage-of-substrate-using-substrate-api-client

I couldn't understand as to why there would be a bad sign when I am repeating signature steps from balance transfer example.

**Comment by kebab-mai-haddi** [comment]
cc @brenzi 

Thanks in advance!

**Comment by brenzi** [comment]
what node version are you running against?

**Comment by clangenb** [comment]
answered here. https://stackoverflow.com/questions/61005569/how-to-write-in-the-storage-of-substrate-using-substrate-api-client/61006857#61006857
