### ISSUE TITLE
Subscriptions and blocking `next()`

### ISSUE THREAD

**Issue by Niederb** [scs/substrate-api-client#638]
Currently subscriptions are blocking in the sync case. See here:
https://github.com/scs/substrate-api-client/blob/4d4f19810f607371cf84e5885f398ab483f5aec9/src/rpc/jsonrpsee_client/subscription.rs#L30-L31
Check whether it is possible to "break" this blocking by calling `unsubscribe()` and if yes also allow the user to use this to cancel calls to `next()` that are stuck.
See this previous discussion: https://github.com/scs/substrate-api-client/pull/635#discussion_r1277185031

**Comment by haerdib** [comment]
With #692 this issue is now obsolete and can be closed
