### ISSUE TITLE
Update outdated dependencies in cargo.tomls

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#671]
There are some outdated dependencies in our .tomls that should be updated.

Example:
![grafik](https://github.com/scs/substrate-api-client/assets/73821294/c5d956aa-e36d-4df4-bc4a-4faeb841fcdb)

**Comment by masapr** [comment]
@Kailai-Wang : I'm not sure what you're question is about. About the dependencies we want to update or the api-client itself?

**Comment by haerdib** [comment]
I believe I know what you meant - you meant the tool in the screenshot, is that correct? I'm using vscode with the extension Rust Exentension Pack, that includes [crates](https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates)

**Comment by Kailai-Wang** [comment]
Thanks @haerdib - yes that's what I mean, sorry that I didn't state it clearly
