### ISSUE TITLE
Tracking: Breaking change in nightly toolchain 05.02.2024

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#712]
There's been a breaking change on rust toolchain nightly version 05.02.2024. 

Important: do not update `curve25519-dalek` v4.1.1 to v4.1.2 before updating the rust toolchain to 05.02.24 or above, as it is not backwards compatible.

The following libraries must be updated to be able to go above toolchain 05.02.2024:
- curve25519-dalek to v4.1.1+, see https://github.com/dalek-cryptography/curve25519-dalek/pull/619
- ahash to v0.8.7 (see https://github.com/tkaitchuck/aHash/pull/183) or wait for merge of https://github.com/tkaitchuck/aHash/pull/201.
- maybe more, we will see.

Currently blocked due to:
- ahash v0.7 required by hashbrown v0.12.3 required by ed25519-zebra v3.1.0 required by sp-core. So we can't update until Parity does or https://github.com/tkaitchuck/aHash/pull/201 is merged.

**Comment by njelich** [comment]
Ahash patch has passed, that should fix other libraries.

https://github.com/tkaitchuck/aHash/pull/201#event-11765907780

**Comment by haerdib** [comment]
Awesome, thank you very much for the heads up!

**Comment by njelich** [comment]
curve25519-dalek patch has also passed.

https://github.com/dalek-cryptography/curve25519-dalek/pull/619

Please retest.
