### ISSUE TITLE
Update to parity branch v1.7.1

### ISSUE THREAD

**Issue by haerdib** [scs/substrate-api-client#727]
https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.7.1

- [x] create branch https://github.com/scs/substrate-api-client/tree/release-polkadot-v1.7.1
- [x] CI passed: https://github.com/scs/substrate-api-client/actions/runs/8097221100
- [x] Update release description: https://github.com/scs/substrate-api-client/releases/tag/v0.17.0

**Comment by haerdib** [comment]
There's a problem with no-std - I'm not sure what's causing it. But master is working, so I'd propose to wait for the next api client release and do the polkadot v1.7.1 release on this api-client release.

**Comment by brenzi** [comment]
By now it will be 1.7.2

Would be great to have this upgrade soon, because Encointer is on 1.7.0 already (depending on crates.io, however, so we may need to wait for you to release this on crates.io as well)

**Comment by haerdib** [comment]
CI has passed, so I'm closing this issue. For the follow-up releases, incl. 1.7.2. and 1.8.0 there are separate issues and are work in progress right now. You can expect the release branches soon.

Regarding crates.io: We will keep you updated in #528
