### ISSUE TITLE
release substrate-client-keystore to crates.io

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#748]
this crate is missing so far. Even if it's a fork of `sc-keystore` we need this because of private fn in upstream

**Comment by Niederb** [comment]
@brenzi We renamed the crate to ac-keystore and it is now available on crates.io: https://crates.io/crates/ac-keystore
Still working on a readme and some meta-infos but I don't expect changes of the code. Please let us know if this works for you

**Comment by masapr** [comment]
implemented, including documentation of new crate.
