### ISSUE TITLE
panic in Justification conversion

### ISSUE THREAD

**Issue by brenzi** [scs/substrate-api-client#811]
this implementation is unsafe:

https://github.com/encointer/substrate-api-client/blob/eddca35c73b5e2e3d0371fa923a0ba605c2f0d61/primitives/src/serde_impls.rs#L290-L299

and is likely the cause of 

https://github.com/integritee-network/worker/issues/1663

I'll propose a PR shortly

**Comment by haerdib** [comment]
With PR https://github.com/scs/substrate-api-client/pull/580 we were able to remove the need for these conversions, if you're looking for a cherry-pick.
