### ISSUE TITLE
Missing field transactionVersion

### ISSUE THREAD

**Issue by DylanVerstraete** [scs/substrate-api-client#96]
Following these docs: https://github.com/scs/substrate-api-client/tree/master/tutorials

Getting following error:
```
Running `target/debug/substrate-api-client-test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `transactionVersion`", line: 1, column: 317)', /home/dylan/.cargo/git/checkouts/substrate-api-client-9327f54164a9792a/999d407/src/lib.rs:163:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by brenzi** [comment]
our tutorial is outdated, I'm sorry. Please work with the examples. these should be up to date and tested by CI

src/examples

**Comment by DylanVerstraete** [comment]
I did some research, seems like the this lib uses
```
[dependencies.sp-core]
version = '2.0.0-alpha.7'
```
Whilst the latest node template uses the rc versions..

**Comment by DylanVerstraete** [comment]
@brenzi  the examples also don't work with latest node template

**Comment by brenzi** [comment]
yes, this api client still depends on alpha.7 and only supports the template at alpha.7 state. Feel free to use [our template fork](https://github.com/scs/substrate-api-client-test-node/tree/v2.0.0-alpha.7).
We won't update the client until substrate 2.0.0 is finally released. Maintenance is too heavy.

**Comment by brenzi** [comment]
@DylanVerstraete our master now supports 2.0.0-rc5, so your issue should be resolved now
