### ISSUE TITLE
Import `sp_runtime::generic::Era`

### ISSUE THREAD

**Issue by shawntabrizi** [scs/substrate-api-client#97]
From the Substrate Technical channel:

> Hello @here,
> I am tring to run light clint code :-
> ```
> 
> 
> use substrate_api_client::{Api, node_metadata::Metadata, XtStatus,compose_extrinsic,extrinsic::xt_primitives::UncheckedExtrinsicV4};
> use sp_core::sr25519;
> use keyring::AccountKeyring;
> use sp_core::crypto::Pair;
> 
> 
> fn main() {
>     // instantiate an Api that connects to the given address
>     let url = "127.0.0.1:9944";
>     // if no signer is set in the whole program, we need to give to Api a specific type instead of an associated type
>     // as during compilation the type needs to be defined.
>     let from = AccountKeyring::Alice.pair();
>     let mut api = Api::new(format!("ws://{}", url)).set_signer(from);
>     let xt: UncheckedExtrinsicV4<_> = compose_extrinsic!( api.clone(),"System", "create_claim");
>     println!("[+] Composed Extrinsic:\n {:?}\n", xt);
>     let signer = AccountKeyring::Alice.pair();
>     api.signer = Some(signer);
>     let tx_hash = api.send_extrinsic(xt.hex_encode(), XtStatus::Finalized).unwrap();
>     println!("[+] Transaction got finalized. Hash: {:?}", tx_hash);
> 
> }
> ```
> 
> But getting error :-
> ```
> error[E0433]: failed to resolve: use of undeclared type or module `sp_runtime`
>   --> src/main.rs:14:39
>    |
> 14 |     let xt: UncheckedExtrinsicV4<_> = compose_extrinsic!( api.clone(),"System", "create_claim");
>    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `sp_runtime`
>    |
>    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> error[E0433]: failed to resolve: use of undeclared type or module `Era`
>   --> src/main.rs:14:39
>    |
> 14 |     let xt: UncheckedExtrinsicV4<_> = compose_extrinsic!( api.clone(),"System", "create_claim");
>    |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `Era`
>    |
>    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
> 
> 
> ```

Cause by: https://github.com/scs/substrate-api-client/blob/ee31f4e6d2004ed9b841f31011516d81b23f6f11/src/extrinsic/mod.rs#L71

Some better re-exporting will solve this

**Comment by Gauthamastro** [comment]
```
[dependencies.sp-runtime]
version = '2.0.0-rc5'
package = "sp-runtime"
default-features=false```

Adding this to Cargo.toml worked for me

**Comment by shawntabrizi** [comment]
@Gauthamastro yes, that will work, but instead this library could simply re-export it so that you dont need to import other libraries that you would not otherwise need.

**Comment by Gauthamastro** [comment]
> @Gauthamastro yes, that will work, but instead this library could simply re-export this dependency so that you dont need to import other libraries that you would not otherwise need.

Sure that will be nice and clean!
